const MONTHS=["Septembre 2026","Octobre 2026","Novembre 2026","Décembre 2026","Janvier 2027","Février 2027","Mars 2027","Avril 2027","Mai 2027","Juin 2027","Juillet 2027","Août 2027","Septembre 2027","Octobre 2027","Novembre 2027","Décembre 2027","Janvier 2028","Février 2028","Mars 2028","Avril 2028","Mai 2028","Juin 2028","Juillet 2028","Août 2028","Septembre 2028"];
const INCOME_CATEGORIES=[
  {id:"salary-b",name:"Salaire Baptiste",budget:1100,owner:"B"},{id:"salary-a",name:"Salaire Anaëlle",budget:1400,owner:"A"},
  {id:"prime",name:"Prime d'activité",budget:200,owner:"common"},{id:"apl",name:"APL",budget:117,owner:"common"},
  {id:"extra-b",name:"Revenu supplémentaire Baptiste",budget:0,owner:"B"},{id:"extra-a",name:"Revenu supplémentaire Anaëlle",budget:0,owner:"A"}
];
const EXPENSE_CATEGORIES=[
  {id:"rent",name:"Loyer (charges comprises)",budget:640,section:"Obligatoires",owner:"common"},{id:"electricity",name:"Électricité",budget:100,section:"Obligatoires",owner:"common"},{id:"groceries",name:"Courses",budget:250,section:"Obligatoires",owner:"common"},{id:"action",name:"Action",budget:60,section:"Obligatoires",owner:"common"},{id:"internet",name:"Box internet",budget:40,section:"Obligatoires",owner:"common"},{id:"mutuelle-b",name:"Mutuelle Baptiste",budget:30,section:"Obligatoires",owner:"B"},{id:"car-insurance",name:"Assurance voiture",budget:50,section:"Obligatoires",owner:"common"},{id:"home-insurance",name:"Assurance habitation",budget:12,section:"Obligatoires",owner:"common"},{id:"phone",name:"Forfait téléphone",budget:10.99,section:"Obligatoires",owner:"B"},{id:"fuel",name:"Essence",budget:140,section:"Obligatoires",owner:"common"},{id:"saving-b",name:"Épargne Baptiste",budget:100,section:"Obligatoires",owner:"B",saving:true},{id:"saving-a",name:"Épargne compagne",budget:100,section:"Obligatoires",owner:"A",saving:true},
  {id:"chatgpt",name:"ChatGPT",budget:25,section:"Abonnements",owner:"B"},{id:"discord",name:"Discord",budget:9.99,section:"Abonnements",owner:"B"},{id:"icloud-b",name:"iCloud+ Baptiste",budget:2.99,section:"Abonnements",owner:"B"},{id:"snap-b",name:"Snapchat+ Baptiste",budget:3.99,section:"Abonnements",owner:"B"},{id:"netflix",name:"Netflix Standard",budget:14.99,section:"Abonnements",owner:"B"},{id:"combat-patrol",name:"Hachette Combat Patrol Premium",budget:51.96,section:"Abonnements",owner:"B"},{id:"spotify",name:"Spotify Duo",budget:17.2,section:"Abonnements",owner:"common"},{id:"snap-a",name:"Snapchat+ Anaëlle",budget:3.99,section:"Abonnements",owner:"A"},{id:"icloud-a",name:"iCloud+ Anaëlle",budget:2.99,section:"Abonnements",owner:"A"},
  {id:"car-maint",name:"Entretien voiture",budget:60,section:"Vie courante",owner:"common"},{id:"home-products",name:"Maison / produits ménagers",budget:40,section:"Vie courante",owner:"common"},{id:"health",name:"Santé / pharmacie",budget:30,section:"Vie courante",owner:"common"},{id:"psy-a",name:"Psy Anaëlle",budget:60,section:"Vie courante",owner:"A"},{id:"clothes",name:"Vêtements / chaussures",budget:40,section:"Vie courante",owner:"common"},{id:"restaurants",name:"Restaurants / fast-food / sorties",budget:120,section:"Vie courante",owner:"common"},{id:"leisure-b",name:"Loisirs / achats perso Baptiste",budget:100,section:"Vie courante",owner:"B"},{id:"leisure-a",name:"Loisirs / achats perso Anaëlle",budget:200,section:"Vie courante",owner:"A"},{id:"gifts",name:"Cadeaux / anniversaires / Noël",budget:50,section:"Vie courante",owner:"common"},{id:"vacations",name:"Vacances / week-ends",budget:75,section:"Vie courante",owner:"common"},{id:"home-equipment",name:"Entretien / équipement logement",budget:40,section:"Vie courante",owner:"common"},{id:"deposit",name:"Caution",budget:0,section:"Vie courante",owner:"common"},{id:"amazon",name:"Amazon",budget:50,section:"Vie courante",owner:"common"},{id:"foire",name:"Foire fouille",budget:0,section:"Vie courante",owner:"common"},{id:"coffee",name:"Café",budget:0,section:"Vie courante",owner:"common"},{id:"zevent",name:"Zevent",budget:0,section:"Vie courante",owner:"common"},{id:"aldi",name:"Aldi",budget:0,section:"Vie courante",owner:"common"},{id:"expense-b",name:"Dépense Baptiste",budget:0,section:"Vie courante",owner:"B"},{id:"expense-a",name:"Dépense Anaëlle",budget:0,section:"Vie courante",owner:"A"}
];
const BASE_INCOME_COUNT=INCOME_CATEGORIES.length;
const BASE_INCOME_NAMES=Object.fromEntries(INCOME_CATEGORIES.map(c=>[c.id,c.name]));
const BASE_INCOME_BUDGETS=Object.fromEntries(INCOME_CATEGORIES.map(c=>[c.id,c.budget]));
const BASE_INCOME_OWNERS=Object.fromEntries(INCOME_CATEGORIES.map(c=>[c.id,c.owner||"common"]));
const BASE_EXPENSE_COUNT=EXPENSE_CATEGORIES.length;
const BASE_EXPENSE_NAMES=Object.fromEntries(EXPENSE_CATEGORIES.map(c=>[c.id,c.name]));
const BASE_EXPENSE_BUDGETS=Object.fromEntries(EXPENSE_CATEGORIES.map(c=>[c.id,c.budget]));
const BASE_EXPENSE_OWNERS=Object.fromEntries(EXPENSE_CATEGORIES.map(c=>[c.id,c.owner||"common"]));

const SEPTEMBER_ACTUAL={
 income:{"salary-b":1043.64,"salary-a":1234.83,"prime":0,"apl":0,"extra-a":1201.75},
 expense:{rent:128,electricity:80,action:60.55,internet:0,"mutuelle-b":0,"car-insurance":0,"home-insurance":12,phone:10.99,fuel:142.77,"saving-b":0,"saving-a":0,chatgpt:25,discord:9.99,"icloud-b":2.99,"snap-b":3.99,netflix:14.99,"combat-patrol":51.96,spotify:17.2,"snap-a":3.99,"icloud-a":2.99,"car-maint":0,"home-products":0,health:0,clothes:0,restaurants:75.3,"leisure-b":0,"leisure-a":0,gifts:0,vacations:0,"home-equipment":0,amazon:46.03,foire:1.99,coffee:3,zevent:1,aldi:1,"expense-b":468,"expense-a":1776.42}
};
const STORAGE_KEY="budget-foyer-v1";
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const euro=n=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(Number(n)||0);
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

function seedState(){
 const transactions=[]; let order=1;
 Object.entries(SEPTEMBER_ACTUAL.income).forEach(([category,amount])=>{if(amount>0)transactions.push({id:"seed-i-"+order++,type:"income",category,amount,date:"2026-09-01",seed:true})});
 Object.entries(SEPTEMBER_ACTUAL.expense).forEach(([category,amount])=>{if(amount>0)transactions.push({id:"seed-e-"+order++,type:"expense",category,amount,date:"2026-09-01",seed:true})});
 return {selectedMonth:"Septembre 2026",transactions,categoryBudgets:{},incomeBudgets:{},categoryOwners:{},incomeCategoryOwners:{},categoryNames:{},incomeCategoryNames:{},customExpenseCategories:[],customIncomeCategories:[],expensePlanChanges:{},incomePlanChanges:{},actualAdjustments:{},incomeActualAdjustments:{},deletedCategoryMonths:{},deletedCategoriesGlobal:[],deletedIncomeCategoryMonths:{},deletedIncomeCategoriesGlobal:[]};
}
function loadState(){
 try{
  const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!(x&&Array.isArray(x.transactions)))return seedState();
  x.categoryBudgets=x.categoryBudgets||{};x.incomeBudgets=x.incomeBudgets||{};x.categoryOwners=x.categoryOwners&&typeof x.categoryOwners==="object"?x.categoryOwners:{};x.incomeCategoryOwners=x.incomeCategoryOwners&&typeof x.incomeCategoryOwners==="object"?x.incomeCategoryOwners:{};x.categoryNames=x.categoryNames&&typeof x.categoryNames==="object"?x.categoryNames:{};x.incomeCategoryNames=x.incomeCategoryNames&&typeof x.incomeCategoryNames==="object"?x.incomeCategoryNames:{};
  x.customExpenseCategories=Array.isArray(x.customExpenseCategories)?x.customExpenseCategories:[];x.customIncomeCategories=Array.isArray(x.customIncomeCategories)?x.customIncomeCategories:[];
  const creationFallback=(category,type)=>{const keys=x.transactions.filter(t=>t.type===type&&t.category===category).map(t=>String(t.date||"").slice(0,7)).filter(Boolean).sort();return keys[0]||monthKey(x.selectedMonth||"Septembre 2026")};
  x.customExpenseCategories=x.customExpenseCategories.map(c=>({...c,createdFrom:c.createdFrom||creationFallback(c.id,"expense")}));x.customIncomeCategories=x.customIncomeCategories.map(c=>({...c,createdFrom:c.createdFrom||creationFallback(c.id,"income")}));
  x.expensePlanChanges=x.expensePlanChanges&&typeof x.expensePlanChanges==="object"?x.expensePlanChanges:{};x.incomePlanChanges=x.incomePlanChanges&&typeof x.incomePlanChanges==="object"?x.incomePlanChanges:{};
  x.deletedCategoryMonths=x.deletedCategoryMonths&&typeof x.deletedCategoryMonths==="object"?x.deletedCategoryMonths:{};x.deletedCategoriesGlobal=Array.isArray(x.deletedCategoriesGlobal)?x.deletedCategoriesGlobal:[];x.deletedIncomeCategoryMonths=x.deletedIncomeCategoryMonths&&typeof x.deletedIncomeCategoryMonths==="object"?x.deletedIncomeCategoryMonths:{};x.deletedIncomeCategoriesGlobal=Array.isArray(x.deletedIncomeCategoriesGlobal)?x.deletedIncomeCategoriesGlobal:[];
  let migrated=false;
  x.transactions.forEach(t=>{if(t?.scope==="forward"){if(!t.seriesId){t.seriesId=t.id;migrated=true}if(!Array.isArray(t.excludedMonths)){t.excludedMonths=[];migrated=true}if(!t.overrides||typeof t.overrides!=="object"||Array.isArray(t.overrides)){t.overrides={};migrated=true}}});
  [["expense","actualAdjustments"],["income","incomeActualAdjustments"]].forEach(([type,prop])=>{const source=x[prop]&&typeof x[prop]==="object"?x[prop]:{};Object.entries(source).forEach(([key,items])=>{Object.entries(items||{}).forEach(([category,delta])=>{delta=Math.round((Number(delta)||0)*100)/100;if(Math.abs(delta)<.005)return;const ownerMap=type==="income"?x.incomeCategoryOwners:x.categoryOwners,baseList=type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES,customList=type==="income"?x.customIncomeCategories:x.customExpenseCategories,owner=ownerMap?.[category]||baseList.find(c=>c.id===category)?.owner||customList.find(c=>c.id===category)?.owner||"common";x.transactions.push({id:`migration-${type}-${key}-${category}-${uid()}`,type,category,owner,amount:delta,date:`${key}-01`,seed:false,adjustment:true,adjustmentLabel:"Ajustement migré"});migrated=true})});x[prop]={}});
  if(migrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(x));
  return x;
 }catch{return seedState()}
}
function applyCategoryState(){
 INCOME_CATEGORIES.splice(BASE_INCOME_COUNT);
 INCOME_CATEGORIES.forEach(c=>{c.name=state.incomeCategoryNames?.[c.id]||BASE_INCOME_NAMES[c.id]||c.name;c.budget=Object.prototype.hasOwnProperty.call(state.incomeBudgets,c.id)?Number(state.incomeBudgets[c.id]):BASE_INCOME_BUDGETS[c.id];c.owner=state.incomeCategoryOwners[c.id]||BASE_INCOME_OWNERS[c.id]||"common"});
 state.customIncomeCategories.forEach(c=>{if(!c||!c.id||!c.name)return;INCOME_CATEGORIES.push({...c,name:state.incomeCategoryNames?.[c.id]||c.name,budget:Object.prototype.hasOwnProperty.call(state.incomeBudgets,c.id)?Number(state.incomeBudgets[c.id]):Number(c.budget)||0,owner:state.incomeCategoryOwners[c.id]||c.owner||"common",custom:true})});
 EXPENSE_CATEGORIES.splice(BASE_EXPENSE_COUNT);
 EXPENSE_CATEGORIES.forEach(c=>{c.name=state.categoryNames?.[c.id]||BASE_EXPENSE_NAMES[c.id]||c.name;c.budget=Object.prototype.hasOwnProperty.call(state.categoryBudgets,c.id)?Number(state.categoryBudgets[c.id]):BASE_EXPENSE_BUDGETS[c.id];c.owner=state.categoryOwners[c.id]||BASE_EXPENSE_OWNERS[c.id]||"common"});
 state.customExpenseCategories.forEach(c=>{if(!c||!c.id||!c.name||!["Obligatoires","Abonnements","Vie courante"].includes(c.section))return;EXPENSE_CATEGORIES.push({...c,name:state.categoryNames?.[c.id]||c.name,budget:Object.prototype.hasOwnProperty.call(state.categoryBudgets,c.id)?Number(state.categoryBudgets[c.id]):Number(c.budget)||0,owner:state.categoryOwners[c.id]||c.owner||"common",custom:true})});
}
let state=loadState();
applyCategoryState();
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function monthKey(label){const parts=label.split(" ");const m={Janvier:"01",Février:"02",Mars:"03",Avril:"04",Mai:"05",Juin:"06",Juillet:"07",Août:"08",Septembre:"09",Octobre:"10",Novembre:"11",Décembre:"12"};return `${parts[1]}-${m[parts[0]]}`}
function labelFromYM(year,month){const names=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"];return `${names[month-1]} ${year}`}
function appendNextMonth(){const last=MONTHS[MONTHS.length-1],key=monthKey(last),[y,m]=key.split("-").map(Number),d=new Date(y,m,1);MONTHS.push(labelFromYM(d.getFullYear(),d.getMonth()+1));return MONTHS[MONTHS.length-1]}
function ensureMonthAvailable(label){if(MONTHS.includes(label))return;const target=monthKey(label);let guard=0;while(monthKey(MONTHS[MONTHS.length-1])<target&&guard++<240)appendNextMonth()}
function planStoreForType(type){return type==="income"?(state.incomePlanChanges=state.incomePlanChanges||{}):(state.expensePlanChanges=state.expensePlanChanges||{})}
function planForCategoryAtKey(c,key,type="expense"){
 const record=planStoreForType(type)[c.id]||{},forward=record.forward||{},month=record.month||{};let budget=Number(c.budget)||0,owner=c.owner||"common";
 const latest=Object.keys(forward).filter(k=>k<=key).sort().pop();if(latest){const v=forward[latest]||{};if(Number.isFinite(Number(v.budget)))budget=Number(v.budget);if(v.owner)owner=v.owner}
 const exact=month[key];if(exact){if(Number.isFinite(Number(exact.budget)))budget=Number(exact.budget);if(exact.owner)owner=exact.owner}
 return {budget,owner}
}
function planForCategory(c,label=state.selectedMonth,type="expense"){return planForCategoryAtKey(c,monthKey(label),type)}
function categoryView(c,type="expense",label=state.selectedMonth){return {...c,...planForCategory(c,label,type)}}
function setCategoryPlan(id,type,budget,owner,scope="forward"){
 const c=(type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES).find(x=>x.id===id);if(!c)return;const key=monthKey(state.selectedMonth),store=planStoreForType(type),record=store[id]||(store[id]={forward:{},month:{}});record.forward=record.forward||{};record.month=record.month||{};
 const value={budget:Math.max(0,Math.round((Number(budget)||0)*100)/100),owner:owner||"common"};
 if(scope==="month")record.month[key]=value;else{record.forward[key]=value;delete record.month[key]}
}
function categoryCreatedFrom(id,type="expense"){const c=(type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES).find(x=>x.id===id);return c?.createdFrom||"2026-09"}
function isCategoryVisible(id,label=state.selectedMonth,type="expense"){const key=monthKey(label),globalDeleted=type==="income"?(state.deletedIncomeCategoriesGlobal||[]):(state.deletedCategoriesGlobal||[]),monthDeleted=type==="income"?(state.deletedIncomeCategoryMonths?.[key]||[]):(state.deletedCategoryMonths?.[key]||[]);return key>=categoryCreatedFrom(id,type)&&!globalDeleted.includes(id)&&!monthDeleted.includes(id)}
function visibleExpenseCategories(label=state.selectedMonth){return EXPENSE_CATEGORIES.filter(c=>!c.saving&&isCategoryVisible(c.id,label,"expense")).map(c=>categoryView(c,"expense",label))}
function visibleSavingCategories(label=state.selectedMonth){return EXPENSE_CATEGORIES.filter(c=>c.saving&&isCategoryVisible(c.id,label,"expense")).map(c=>categoryView(c,"expense",label))}
function visibleIncomeCategories(label=state.selectedMonth){return INCOME_CATEGORIES.filter(c=>isCategoryVisible(c.id,label,"income")).map(c=>categoryView(c,"income",label))}
function recurringOccurrenceDate(t,key){const raw=String(t.date||"");const day=Math.max(1,Math.min(31,Number(raw.slice(8,10))||1)),[y,m]=key.split("-").map(Number),last=new Date(y,m,0).getDate();return `${key}-${String(Math.min(day,last)).padStart(2,"0")}`}
function previousMonthKey(key){const [y,m]=key.split("-").map(Number),d=new Date(y,m-2,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function recurringSeriesId(t){return t?.seriesId||t?.id||""}
function recurringRoot(sourceId){return state.transactions.find(t=>t.id===sourceId&&t.scope==="forward")||null}
function recurringSeriesRootsFromSource(sourceId){const root=recurringRoot(sourceId);if(!root)return[];const seriesId=recurringSeriesId(root);return state.transactions.filter(t=>t.scope==="forward"&&recurringSeriesId(t)===seriesId)}
function transactionsForMonthKey(key){return state.transactions.flatMap(t=>{const start=String(t.date||"").slice(0,7);if(t.scope==="forward"){if(!start||start>key||(t.endMonth&&key>t.endMonth)||(t.excludedMonths||[]).includes(key))return[];const override=t.overrides?.[key]||{};return[{...t,...override,id:`${t.id}@${key}`,sourceId:t.id,seriesId:recurringSeriesId(t),date:recurringOccurrenceDate(t,key),recurringOccurrence:true}]}return start===key?[t]:[]})}
function getMonthTransactions(){return transactionsForMonthKey(monthKey(state.selectedMonth))}
const LEGACY_CATEGORY_DEFS={"extra-1":{id:"extra-1",name:"Revenu supplémentaire 1",owner:"common",legacy:true,type:"income"},"extra-2":{id:"extra-2",name:"Revenu supplémentaire 2",owner:"common",legacy:true,type:"income"},"expense-1":{id:"expense-1",name:"Dépense 1",owner:"common",section:"Vie courante",legacy:true,type:"expense"},"expense-2":{id:"expense-2",name:"Dépense 2",owner:"common",section:"Vie courante",legacy:true,type:"expense"},"expense-3":{id:"expense-3",name:"Dépense 3",owner:"common",section:"Vie courante",legacy:true,type:"expense"},"expense-4":{id:"expense-4",name:"Dépense 4",owner:"common",section:"Vie courante",legacy:true,type:"expense"}};
function catById(id,type){return (type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES).find(c=>c.id===id)||(LEGACY_CATEGORY_DEFS[id]?.type===type?LEGACY_CATEGORY_DEFS[id]:null)}
function totalsByCategoryAtKey(type,key){const map={};transactionsForMonthKey(key).filter(t=>t.type===type).forEach(t=>map[t.category]=(map[t.category]||0)+(Number(t.amount)||0));return map}
function totalsByCategory(type){return totalsByCategoryAtKey(type,monthKey(state.selectedMonth))}
function sum(list){return list.reduce((a,b)=>a+b,0)}
function shareAmount(owner,amount,person){if(owner==="common")return amount/2;if(owner===person)return amount;return 0}
function transactionOwner(t){if(t.owner)return t.owner;const c=catById(t.category,t.type);if(!c)return "common";return planForCategoryAtKey(c,String(t.date||"").slice(0,7)||monthKey(state.selectedMonth),t.type).owner||"common"}
function actualForCategoryAtMonth(id,key,type="expense"){return Math.round(sum(transactionsForMonthKey(key).filter(t=>t.type===type&&t.category===id).map(t=>Number(t.amount)||0))*100)/100}
function cumulativeCategoryActual(id,type="expense",throughLabel=state.selectedMonth){const through=monthKey(throughLabel);return MONTHS.map(monthKey).filter(key=>key<=through).reduce((total,key)=>total+actualForCategoryAtMonth(id,key,type),0)}
function metricsForMonth(label=state.selectedMonth){
 const key=monthKey(label),tx=transactionsForMonthKey(key),incMap=totalsByCategoryAtKey("income",key),expMap=totalsByCategoryAtKey("expense",key);
 const income=sum(tx.filter(t=>t.type==="income").map(t=>Number(t.amount)||0));
 const expense=sum(tx.filter(t=>t.type==="expense"&&!catById(t.category,"expense")?.saving).map(t=>Number(t.amount)||0));
 const saving=sum(tx.filter(t=>t.type==="expense"&&catById(t.category,"expense")?.saving).map(t=>Number(t.amount)||0));
 const plannedIncome=sum(visibleIncomeCategories(label).map(c=>c.budget)),plannedExpense=sum(visibleExpenseCategories(label).map(c=>c.budget)),plannedSaving=sum(visibleSavingCategories(label).map(c=>c.budget));
 let incomeB=0,incomeA=0,expenseB=0,expenseA=0,savingBShare=0,savingAShare=0;
 tx.forEach(t=>{const owner=transactionOwner(t),amount=Number(t.amount)||0;if(t.type==="income"){incomeB+=shareAmount(owner,amount,"B");incomeA+=shareAmount(owner,amount,"A")}else if(catById(t.category,"expense")?.saving){savingBShare+=shareAmount(owner,amount,"B");savingAShare+=shareAmount(owner,amount,"A")}else{expenseB+=shareAmount(owner,amount,"B");expenseA+=shareAmount(owner,amount,"A")}});
 const savingsBMonth=expMap["saving-b"]||0,savingsAMonth=expMap["saving-a"]||0,savingsB=cumulativeCategoryActual("saving-b","expense",label),savingsA=cumulativeCategoryActual("saving-a","expense",label);
 return {label,key,tx,incMap,expMap,income,expense,saving,plannedIncome,plannedExpense,plannedSaving,balance:income-expense-saving,plannedBalance:plannedIncome-plannedExpense-plannedSaving,incomeB,incomeA,expenseB,expenseA,savingBShare,savingAShare,restB:incomeB-expenseB-savingBShare,restA:incomeA-expenseA-savingAShare,savingsB,savingsA,savingsBMonth,savingsAMonth};
}
function metrics(){return metricsForMonth(state.selectedMonth)}
function render(){
 const m=metrics();
 document.getElementById("balanceValue").innerHTML=`${euro(m.balance).replace("€","")}<small>€</small>`;
 document.querySelector("#plannedRest .meta-value").textContent=euro(m.plannedBalance);
 const delta=m.balance-m.plannedBalance,deltaEl=document.getElementById("balanceDelta");
 deltaEl.classList.remove("positive","negative","neutral");
 deltaEl.classList.add(delta>0.005?"positive":delta<-0.005?"negative":"neutral");
 document.querySelector("#balanceDelta .meta-value").textContent=`${delta>0.005?"+":""}${euro(delta)}`;
 document.getElementById("incomeTotal").textContent=euro(m.income);document.getElementById("incomePlanned").textContent=`Prévu ${euro(m.plannedIncome)}`;
 document.getElementById("expenseTotal").textContent=euro(m.expense);document.getElementById("expensePlanned").textContent=`Budget ${euro(m.plannedExpense)}`;
 document.getElementById("saveB").textContent=euro(m.savingsB);document.getElementById("saveA").textContent=euro(m.savingsA);document.getElementById("saveBMonth").textContent=euro(m.savingsBMonth);document.getElementById("saveAMonth").textContent=euro(m.savingsAMonth);
 document.getElementById("restB").textContent=euro(m.restB);document.getElementById("restA").textContent=euro(m.restA);
 document.getElementById("personBDetail").textContent=`${euro(m.incomeB)} de revenus · ${euro(m.expenseB)} dépensés · ${euro(m.savingBShare)} épargnés`;
 document.getElementById("personADetail").textContent=`${euro(m.incomeA)} de revenus · ${euro(m.expenseA)} dépensés · ${euro(m.savingAShare)} épargnés`;
 renderSections(m);renderTop(m);renderRecent(m);renderCategories(m);renderHistory(m);renderTracking();
 document.getElementById("transactionCount").textContent=`${m.tx.length} opération${m.tx.length>1?"s":""}`;
}
function renderSections(m){const sections=["Obligatoires","Abonnements","Vie courante"];document.getElementById("sectionCards").innerHTML=sections.map(s=>{const cats=visibleExpenseCategories().filter(c=>c.section===s),planned=sum(cats.map(c=>c.budget)),actual=sum(EXPENSE_CATEGORIES.filter(c=>!c.saving&&c.section===s).map(c=>m.expMap[c.id]||0))+sum(Object.values(LEGACY_CATEGORY_DEFS).filter(c=>c.type==="expense"&&c.section===s).map(c=>m.expMap[c.id]||0)),pct=planned?actual/planned*100:(actual?100:0),over=actual>planned;return `<article class="card budget-card"><div class="budget-card-head"><h3>${s}</h3><span class="${over?'row-value exp':'row-sub'}">${Math.round(pct)}%</span></div><div class="nums"><strong>${euro(actual)}</strong> / ${euro(planned)}</div><div class="progress ${over?'over':''}"><span style="width:${Math.min(pct,100)}%"></span></div><div class="budget-foot">${over?`Dépassement de ${euro(actual-planned)}`:`Il reste ${euro(Math.max(planned-actual,0))}`}</div></article>`}).join("")}
function renderTop(m){const items=visibleExpenseCategories().map(c=>{const actual=m.expMap[c.id]||0,pct=c.budget>0?actual/c.budget*100:(actual>0?999:0);return {...c,actual,pct}}).filter(c=>c.actual>0&&(c.pct>=75||c.budget===0)).sort((a,b)=>b.pct-a.pct).slice(0,6);document.getElementById("topCategories").innerHTML=items.length?items.map(c=>{const over=c.budget>0&&c.actual>c.budget,remaining=c.budget>0?c.budget-c.actual:0,label=over?`Dépassé de ${euro(Math.abs(remaining))}`:c.budget>0?`Il reste ${euro(Math.max(remaining,0))}`:"Aucun budget prévu",pill=over?"danger":c.pct>=90?"warn":"ok";return `<div class="row"><div class="watch-status"><div class="watch-copy"><div class="watch-title">${escapeHtml(c.name)}</div><div class="watch-sub">${euro(c.actual)} / ${euro(c.budget)}</div></div><span class="watch-pill ${pill}">${label}</span></div></div>`}).join(""):`<div class="empty">Tout est dans les budgets ce mois-ci.</div>`}
function sortedTransactions(m){return [...m.tx].sort((a,b)=>(b.date||"").localeCompare(a.date||"")||String(b.id).localeCompare(String(a.id)))}
function transactionPresentation(t){const c=catById(t.category,t.type),amount=Number(t.amount)||0,saving=t.type==="expense"&&!!c?.saving;let cls,icon,prefix;if(saving){cls="saving";icon="↗";prefix=amount>=0?"+":"−"}else if(t.type==="income"){cls=amount>=0?"inc":"exp";icon=amount>=0?"+":"−";prefix=amount>=0?"+":"−"}else{cls=amount>=0?"exp":"inc";icon=amount>=0?"−":"+";prefix=amount>=0?"−":"+"}return {c,amount,saving,cls,icon,prefix}}
function transactionTitle(t){const c=catById(t.category,t.type),label=String(t.label||"").trim();return label||c?.name||"Catégorie"}
function transactionContext(t,short=false){const who=ownerLabel(transactionOwner(t)),date=new Date((t.date||transactionDateForSelectedMonth())+'T12:00:00').toLocaleDateString('fr-FR',short?{day:'2-digit',month:'short'}:{day:'2-digit',month:'long',year:'numeric'}),c=catById(t.category,t.type),categoryPrefix=String(t.label||"").trim()&&c?.name?`${escapeHtml(c.name)} · `:"";if(t.adjustment)return `${categoryPrefix}${escapeHtml(t.adjustmentLabel||"Ajustement manuel")} · ${date} · ${who}`;if(t.seed)return `${categoryPrefix}Import du tableur · ${who}`;if(t.recurringOccurrence||t.scope==="forward")return `${categoryPrefix}Récurrent · ${date} · ${who}`;return `${categoryPrefix}${date} · ${who}`}
function historyEntries(m){const sorted=sortedTransactions(m),seen=new Set(),entries=[];for(const t of sorted){if(t.bulkGroupId){if(seen.has(t.bulkGroupId))continue;const tx=sorted.filter(x=>x.bulkGroupId===t.bulkGroupId);seen.add(t.bulkGroupId);entries.push({group:true,id:t.bulkGroupId,label:t.bulkLabel||t.adjustmentLabel||"Mise à jour groupée",tx,date:t.date})}else entries.push({group:false,tx:t,date:t.date})}return entries}
function groupPresentation(entry){const amount=sum(entry.tx.map(t=>Number(t.amount)||0)),type=entry.tx.every(t=>t.type==="income")?"income":entry.tx.every(t=>catById(t.category,t.type)?.saving)?"saving":"expense",cls=type==="income"?(amount>=0?"inc":"exp"):type==="saving"?"saving":(amount>=0?"exp":"inc"),prefix=type==="expense"?(amount>=0?"−":"+"):(amount>=0?"+":"−"),icon=type==="income"?"+":type==="saving"?"↗":"−";return {amount,type,cls,prefix,icon}}
function renderRecent(m){const entries=historyEntries(m).slice(0,6);document.getElementById("recentTransactions").innerHTML=entries.length?entries.map(entry=>{if(entry.group){const p=groupPresentation(entry);return `<div class="row"><div class="row-main"><div class="row-title">${escapeHtml(entry.label)}</div><div class="row-sub">${entry.tx.length} opérations · ${new Date((entry.date||transactionDateForSelectedMonth())+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'short'})}</div></div><div class="row-value ${p.cls}">${p.prefix}${euro(Math.abs(p.amount))}</div></div>`}const t=entry.tx,p=transactionPresentation(t);return `<div class="row"><div class="row-main"><div class="row-title">${escapeHtml(transactionTitle(t))}</div><div class="row-sub">${transactionContext(t,true)}</div></div><div class="row-value ${p.cls}">${p.prefix}${euro(Math.abs(p.amount))}</div></div>`}).join(""):`<div class="empty">Aucun mouvement pour ce mois.</div>`}
function categoryRow(c,actual,type){const isSaving=type==="expense"&&!!c.saving,actualLabel=type==="income"?"Modifier le montant réel reçu":isSaving?"Modifier le montant réellement épargné":"Modifier le montant réel dépensé";return `<div class="cat-item"><div class="cat-line"><div class="cat-name">${escapeHtml(c.name)}</div><div class="cat-side"><div class="cat-amount">${euro(actual)}</div><button class="edit-budget" type="button" data-edit-actual="${escapeHtml(c.id)}" data-category-type="${type}" aria-label="${actualLabel} pour ${escapeHtml(c.name)}" title="Modifier le réel"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></button></div></div><div class="cat-meta"><span class="cat-planned">Prévu ${euro(c.budget)}<button class="edit-planned" type="button" data-edit-planned="${escapeHtml(c.id)}" data-category-type="${type}" aria-label="Modifier le budget prévu de ${escapeHtml(c.name)}" title="Modifier le prévu"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></button><button class="delete-category" type="button" data-delete-category="${escapeHtml(c.id)}" data-category-type="${type}" aria-label="Supprimer ${escapeHtml(c.name)}" title="Supprimer ce champ"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v5M14 11v5"/></svg></button></span><span>${ownerLabel(c.owner)}</span></div></div>`}
function archivedCategoryRow(c,actual,type){return `<div class="cat-item archived"><div class="cat-line"><div class="cat-name">${escapeHtml(c.name)} <span class="archive-badge">Archivée</span></div><div class="cat-amount">${euro(actual)}</div></div><div class="cat-meta"><span>Mouvements conservés pour expliquer le total</span><span>${ownerLabel(transactionOwner({category:c.id,type,date:`${monthKey(state.selectedMonth)}-01`}))}</span></div></div>`}
function archivedCategoriesFor(type,section,m){const base=type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES,legacy=Object.values(LEGACY_CATEGORY_DEFS).filter(c=>c.type===type),list=[...base,...legacy],totals=type==="income"?m.incMap:m.expMap;return list.filter(c=>{if(type==="expense"){if(section==="__savings__"&&!c.saving)return false;if(section!=="__savings__"&&(c.saving||c.section!==section))return false}const hidden=c.legacy||!isCategoryVisible(c.id,state.selectedMonth,type);return hidden&&Math.abs(totals[c.id]||0)>.005}).map(c=>c.legacy?c:categoryView(c,type))}
function archivedBlock(cats,totals,type){return cats.length?`<div class="archived-wrap"><div class="archived-label">Archivées ce mois</div>${cats.map(c=>archivedCategoryRow(c,totals[c.id]||0,type)).join("")}</div>`:""}
function categoryBulkButtons(type,section,label){return `<div class="cat-section-actions"><button class="cat-bulk fill" type="button" data-bulk-action="fill" data-category-type="${type}" data-section="${escapeHtml(section||"")}" title="Mettre tous les montants réels au niveau du prévu" aria-label="Tout remplir dans ${escapeHtml(label)}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12.5l4 4L19 6.5"/></svg><span>Tout remplir</span></button><button class="cat-bulk clear" type="button" data-bulk-action="clear" data-category-type="${type}" data-section="${escapeHtml(section||"")}" title="Remettre tous les montants réels à zéro" aria-label="Tout vider dans ${escapeHtml(label)}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16"/><path d="M9 7V5h6v2"/><path d="M18 7l-1 12H7L6 7"/></svg><span>Tout vider</span></button></div>`}
function renderCategories(m){
 const incomeCats=visibleIncomeCategories(),incomeActual=m.income,incomePlanned=sum(incomeCats.map(c=>c.budget));
 const incomeArchived=archivedCategoriesFor("income","",m),incomeCard=`<article class="card cat-section income-card"><div class="cat-section-head"><div class="cat-section-title">Revenus<div class="cat-section-total">${euro(incomeActual)} / ${euro(incomePlanned)}</div></div>${categoryBulkButtons("income","","Revenus")}</div><div class="income-list">${incomeCats.map(c=>categoryRow(c,m.incMap[c.id]||0,"income")).join("")}</div>${archivedBlock(incomeArchived,m.incMap,"income")}<button class="add-category" type="button" data-add-category="Revenus" data-category-type="income">＋ Ajouter un champ</button></article>`;
 const sections=["Obligatoires","Abonnements","Vie courante"];
 const expenseCards=sections.map(section=>{const cats=visibleExpenseCategories().filter(c=>c.section===section),archived=archivedCategoriesFor("expense",section,m),actual=sum(EXPENSE_CATEGORIES.filter(c=>!c.saving&&c.section===section).map(c=>m.expMap[c.id]||0))+sum(Object.values(LEGACY_CATEGORY_DEFS).filter(c=>c.type==="expense"&&c.section===section).map(c=>m.expMap[c.id]||0)),planned=sum(cats.map(c=>c.budget));return `<article class="card cat-section"><div class="cat-section-head"><div class="cat-section-title">${section}<div class="cat-section-total">${euro(actual)} / ${euro(planned)}</div></div>${categoryBulkButtons("expense",section,section)}</div>${cats.map(c=>categoryRow(c,m.expMap[c.id]||0,"expense")).join("")}${archivedBlock(archived,m.expMap,"expense")}<button class="add-category" type="button" data-add-category="${section}" data-category-type="expense">＋ Ajouter un champ</button></article>`}).join("");
 const savingCats=visibleSavingCategories(),savingArchived=archivedCategoriesFor("expense","__savings__",m),savingActual=m.saving,savingPlanned=sum(savingCats.map(c=>c.budget));
 const savingCard=`<article class="card cat-section saving-card"><div class="cat-section-head"><div class="cat-section-title">Épargne<div class="cat-section-total">${euro(savingActual)} / ${euro(savingPlanned)}</div></div>${categoryBulkButtons("expense","__savings__","Épargne")}</div><div class="income-list">${savingCats.map(c=>categoryRow(c,m.expMap[c.id]||0,"expense")).join("")}</div>${archivedBlock(savingArchived,m.expMap,"expense")}<button class="add-category saving-add" type="button" data-add-saving="1">＋ Ajouter une épargne</button></article>`;
 document.getElementById("categoryGrid").innerHTML=`<section class="category-group"><div class="category-group-head"><h2>Revenus</h2><span>Entrées d’argent · réel / prévu</span></div><div class="category-cards income-cards">${incomeCard}</div></section><section class="category-group"><div class="category-group-head"><h2>Dépenses</h2><span>Argent réellement consommé · hors épargne</span></div><div class="category-cards">${expenseCards}</div></section><section class="category-group saving-group"><div class="category-group-head"><h2>Épargne</h2><span>Argent mis de côté · déduit du disponible</span></div><div class="category-cards income-cards">${savingCard}</div></section>`;
}
function ownerLabel(o){return o==="common"?"À deux":o==="B"?"Baptiste":"Anaëlle"}
function renderHistory(m){const entries=historyEntries(m);document.getElementById("historyList").innerHTML=entries.length?entries.map(entry=>{if(entry.group){const p=groupPresentation(entry),date=new Date((entry.date||transactionDateForSelectedMonth())+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'long',year:'numeric'});return `<div class="history-group" data-history-group="${entry.id}"><div class="history-row"><div class="history-icon ${p.type}">${p.icon}</div><div><div class="history-title">${escapeHtml(entry.label)}</div><div class="history-date">${entry.tx.length} opérations · ${date} <button class="history-toggle" type="button" data-toggle-group="${entry.id}">Voir le détail</button></div></div><div class="history-amount row-value ${p.cls}">${p.prefix}${euro(Math.abs(p.amount))}</div><div class="history-actions"><button class="history-delete" title="Supprimer ce groupe" data-delete-group="${entry.id}" aria-label="Supprimer ce groupe">×</button></div></div><div class="history-group-details">${entry.tx.map(t=>{const tp=transactionPresentation(t);return `<div class="history-detail-row"><span>${escapeHtml(transactionTitle(t))}</span><strong>${tp.prefix}${euro(Math.abs(tp.amount))}</strong></div>`}).join("")}</div></div>`}const t=entry.tx,p=transactionPresentation(t),recurring=!!t.recurringOccurrence||t.scope==="forward",actions=recurring?`<div class="history-actions"><button class="history-edit" type="button" title="Modifier la récurrence" aria-label="Modifier la récurrence" data-edit-recurring="${t.sourceId||t.id}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></button><button class="history-delete" title="Supprimer la récurrence" aria-label="Supprimer la récurrence" data-delete-recurring="${t.sourceId||t.id}">×</button></div>`:`<div class="history-actions"><button class="history-delete" title="Supprimer" aria-label="Supprimer l’opération" data-delete="${t.id}">×</button></div>`;return `<div class="history-row"><div class="history-icon ${p.saving?'saving':t.type}">${p.icon}</div><div><div class="history-title">${escapeHtml(transactionTitle(t))}</div><div class="history-date">${transactionContext(t,false)}</div></div><div class="history-amount row-value ${p.cls}">${p.prefix}${euro(Math.abs(p.amount))}</div>${actions}</div>`}).join(""):`<div class="empty">Aucune opération sur ce mois.</div>`}


const customSelects=new Map();
function closeCustomSelects(except=null){
  customSelects.forEach((ui)=>{if(ui.root!==except){ui.root.classList.remove("open");ui.trigger.setAttribute("aria-expanded","false")}})
}
function buildCustomSelect(select){
  const root=document.querySelector(`.custom-select[data-select="${select.id}"]`);if(!root)return null;
  const trigger=root.querySelector(".custom-select-trigger"),valueEl=root.querySelector(".custom-select-value"),menu=root.querySelector(".custom-select-menu"),scroller=menu.querySelector(".custom-select-scroll");
  const check=`<span class="custom-select-check" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 12.5l4 4L18 8"/></svg></span>`;
  function rebuild(){
    const parts=[];
    [...select.children].forEach(node=>{
      if(node.tagName==="OPTGROUP"){
        parts.push(`<div class="custom-select-group">${escapeHtml(node.label)}</div>`);
        [...node.children].forEach(opt=>{if(opt.disabled&&opt.value==="")return;const create=opt.value==="__create__"?" create-option":"";parts.push(`<button type="button" class="custom-select-option${create}" role="option" data-value="${escapeHtml(opt.value)}">${check}<span style="flex:1">${escapeHtml(opt.textContent)}</span></button>`)});
      } else if(node.tagName==="OPTION"){if(node.disabled&&node.value==="")return;const create=node.value==="__create__"?" create-option":"";parts.push(`<button type="button" class="custom-select-option${create}" role="option" data-value="${escapeHtml(node.value)}">${check}<span style="flex:1">${escapeHtml(node.textContent)}</span></button>`)}
    });
    scroller.innerHTML=parts.join("");sync();
  }
  function sync(){
    const selected=select.options[select.selectedIndex];
    valueEl.textContent=selected?selected.textContent:"Choisir";
    scroller.querySelectorAll(".custom-select-option").forEach(o=>{const active=o.dataset.value===select.value;o.classList.toggle("selected",active);o.setAttribute("aria-selected",active?"true":"false")});
  }
  trigger.addEventListener("click",e=>{e.stopPropagation();const willOpen=!root.classList.contains("open");closeCustomSelects(root);root.classList.toggle("open",willOpen);trigger.setAttribute("aria-expanded",willOpen?"true":"false");if(willOpen){const sel=scroller.querySelector(".selected");sel?.scrollIntoView({block:"nearest"})}});
  menu.addEventListener("click",e=>{const option=e.target.closest(".custom-select-option");if(!option)return;select.value=option.dataset.value;select.dispatchEvent(new Event("change",{bubbles:true}));root.classList.remove("open");trigger.setAttribute("aria-expanded","false")});
  trigger.addEventListener("keydown",e=>{if(["ArrowDown","ArrowUp","Enter"," "].includes(e.key)){e.preventDefault();root.classList.add("open");trigger.setAttribute("aria-expanded","true")}if(e.key==="Escape"){root.classList.remove("open");trigger.setAttribute("aria-expanded","false")}});
  select.addEventListener("change",sync);
  const api={root,trigger,menu,rebuild,sync};customSelects.set(select,api);rebuild();return api;
}
function rebuildCustomSelect(select){customSelects.get(select)?.rebuild()}
function syncCustomSelect(select){customSelects.get(select)?.sync()}
document.addEventListener("click",()=>closeCustomSelects());

const monthSelect=document.getElementById("monthSelect"),prevMonthBtn=document.getElementById("prevMonth"),nextMonthBtn=document.getElementById("nextMonth");ensureMonthAvailable(state.selectedMonth);MONTHS.forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x;monthSelect.appendChild(o)});monthSelect.value=state.selectedMonth;buildCustomSelect(monthSelect);
function updateMonthNav(){const i=MONTHS.indexOf(state.selectedMonth);prevMonthBtn.disabled=i<=0;nextMonthBtn.disabled=false}
function moveMonth(step){let i=MONTHS.indexOf(state.selectedMonth),next=i+step;if(next<0)return;if(next>=MONTHS.length){const label=appendNextMonth(),o=document.createElement("option");o.value=label;o.textContent=label;monthSelect.appendChild(o);rebuildCustomSelect(monthSelect)}state.selectedMonth=MONTHS[next];monthSelect.value=state.selectedMonth;syncCustomSelect(monthSelect);saveState();updateMonthNav();render()}
monthSelect.addEventListener("change",e=>{state.selectedMonth=e.target.value;saveState();updateMonthNav();render()});
prevMonthBtn.addEventListener("click",()=>moveMonth(-1));nextMonthBtn.addEventListener("click",()=>moveMonth(1));
updateMonthNav();
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.getElementById(btn.dataset.tab).classList.add("active")}));

const categoryGrid=document.getElementById("categoryGrid"),categoryEditBackdrop=document.getElementById("categoryEditBackdrop"),categoryEditTitle=document.getElementById("categoryEditTitle"),categoryEditKind=document.getElementById("categoryEditKind"),categoryNameField=document.getElementById("categoryNameField"),categoryNameInput=document.getElementById("categoryNameInput"),categorySectionField=document.getElementById("categorySectionField"),categorySectionButtons=[...document.querySelectorAll("[data-category-section]")],categoryOwnerField=document.getElementById("categoryOwnerField"),categoryOwnerLabel=document.getElementById("categoryOwnerLabel"),categoryOwnerButtons=[...document.querySelectorAll("[data-category-owner]")],categoryBudgetInput=document.getElementById("categoryBudgetInput"),categoryAmountLabel=document.getElementById("categoryAmountLabel"),categoryPlanScopeField=document.getElementById("categoryPlanScopeField"),categoryPlanScopeButtons=[...document.querySelectorAll("[data-plan-scope]")],categoryPlanScopeHint=document.getElementById("categoryPlanScopeHint"),saveCategoryEdit=document.getElementById("saveCategoryEdit");
let categoryEditMode="planned",categoryEditId=null,categoryEditSection=null,categoryEditType="expense",categoryEditOwner="common",categoryPlanScope="forward",categoryEditOrigin="categories";
function setCategoryEditOwner(owner){categoryEditOwner=owner;categoryOwnerButtons.forEach(b=>b.classList.toggle("active",b.dataset.categoryOwner===owner))}
function setCategoryEditSection(section){categoryEditSection=section;categorySectionButtons.forEach(b=>b.classList.toggle("active",b.dataset.categorySection===section))}
function setCategoryPlanScope(scope){categoryPlanScope=scope;categoryPlanScopeButtons.forEach(b=>b.classList.toggle("active",b.dataset.planScope===scope));categoryPlanScopeHint.textContent=scope==="month"?`Ce changement concerne uniquement ${state.selectedMonth}.`:`Le nouveau prévu s'appliquera à ${state.selectedMonth} et aux mois suivants.`}
categoryOwnerButtons.forEach(b=>b.addEventListener("click",()=>setCategoryEditOwner(b.dataset.categoryOwner)));categorySectionButtons.forEach(b=>b.addEventListener("click",()=>setCategoryEditSection(b.dataset.categorySection)));categoryPlanScopeButtons.forEach(b=>b.addEventListener("click",()=>setCategoryPlanScope(b.dataset.planScope)));
function categoriesForType(type){return type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES}
function openCategoryEditor(id=null,section=null,mode="planned",type="expense",origin="categories"){
 closeCustomSelects();categoryEditId=id;categoryEditSection=section;categoryEditMode=id?mode:"add";categoryEditType=type;categoryEditOrigin=origin;const ownerEditable=categoryEditMode==="add"||categoryEditMode==="planned";categoryOwnerField.style.display=ownerEditable?"block":"none";categoryPlanScopeField.style.display=categoryEditMode==="planned"?"block":"none";categorySectionField.style.display=categoryEditMode==="add"&&type==="expense"&&origin==="transaction"?"block":"none";categoryOwnerLabel.textContent=type==="income"?"ATTRIBUTION DU REVENU":"ATTRIBUTION DE LA DÉPENSE";
 if(id){const base=categoriesForType(type).find(x=>x.id===id);if(!base)return;const c=categoryView(base,type);categoryEditKind.textContent=c.name;categoryNameField.style.display=mode==="planned"?"block":"none";categoryNameInput.value=c.name;if(ownerEditable)setCategoryEditOwner(c.owner||"common");if(mode==="actual"){const m=metrics(),a=(type==="income"?m.incMap:m.expMap)[c.id]||0,isSaving=type==="expense"&&!!base.saving;categoryEditTitle.textContent=isSaving?"Modifier l’épargne":type==="income"?"Modifier le revenu réel":"Modifier le réel";categoryAmountLabel.textContent=isSaving?"MONTANT RÉEL ÉPARGNÉ":type==="income"?"MONTANT RÉEL REÇU":"MONTANT RÉEL DÉPENSÉ";categoryBudgetInput.value=Number(a).toFixed(2);saveCategoryEdit.textContent=isSaving?"Enregistrer l’épargne":"Enregistrer le réel";saveCategoryEdit.className=type==="income"||isSaving?"btn btn-income save":"btn btn-ghost save"}else{setCategoryPlanScope("forward");categoryEditTitle.textContent=base.saving?"Modifier l’épargne prévue":"Modifier le prévu";categoryAmountLabel.textContent=base.saving?"MONTANT D’ÉPARGNE PRÉVU":"MONTANT PRÉVU";categoryBudgetInput.value=Number(c.budget||0).toFixed(2);saveCategoryEdit.textContent="Enregistrer le prévu";saveCategoryEdit.className="btn btn-income save"}}
 else{setCategoryEditOwner("common");if(type==="expense")setCategoryEditSection(section||"Vie courante");categoryPlanScopeField.style.display="none";categoryEditTitle.textContent=type==="income"?"Créer un revenu":"Créer une dépense";categoryEditKind.textContent=origin==="transaction"?"Nouveau champ pour cette opération":section||"Catégorie";categoryNameField.style.display="block";categoryNameInput.value="";categoryAmountLabel.textContent="MONTANT PRÉVU";categoryBudgetInput.value="";saveCategoryEdit.textContent="Créer le champ";saveCategoryEdit.className="btn btn-income save"}
 categoryEditBackdrop.classList.add("open");categoryEditBackdrop.setAttribute("aria-hidden","false");setTimeout(()=>{(id?categoryBudgetInput:categoryNameInput).focus()},70);
}
function closeCategoryEditor(){categoryEditBackdrop.classList.remove("open");categoryEditBackdrop.setAttribute("aria-hidden","true")}
function setCategoryActual(id,amount,type="expense",label="Ajustement manuel",meta={}){
 const current=totalsByCategory(type)[id]||0,target=Math.max(0,Math.round((Number(amount)||0)*100)/100),delta=Math.round((target-current)*100)/100;if(Math.abs(delta)<.005)return false;const c=catById(id,type),owner=c?planForCategory(c,state.selectedMonth,type).owner:"common";state.transactions.push({id:uid(),type,category:id,owner,amount:delta,date:transactionDateForSelectedMonth(),seed:false,adjustment:true,adjustmentLabel:label,...meta});return true
}
function setSectionActual(type,section,mode){const cats=type==="income"?visibleIncomeCategories():section==="__savings__"?visibleSavingCategories():visibleExpenseCategories().filter(c=>c.section===section),action=mode==="fill"?"Remplissage automatique":"Remise à zéro",groupName=type==="income"?"Revenus":section==="__savings__"?"Épargne":section,groupId=`bulk-${uid()}`,bulkLabel=`${groupName} · ${mode==="fill"?"tout remplir":"tout vider"}`;cats.forEach(c=>setCategoryActual(c.id,mode==="fill"?c.budget:0,type,action,{bulkGroupId:groupId,bulkLabel}));saveState();render()}
categoryGrid.addEventListener("click",e=>{const bulk=e.target.closest("[data-bulk-action]");if(bulk){setSectionActual(bulk.dataset.categoryType||"expense",bulk.dataset.section||"",bulk.dataset.bulkAction);return}const actual=e.target.closest("[data-edit-actual]");if(actual){openCategoryEditor(actual.dataset.editActual,null,"actual",actual.dataset.categoryType||"expense");return}const planned=e.target.closest("[data-edit-planned]");if(planned){openCategoryEditor(planned.dataset.editPlanned,null,"planned",planned.dataset.categoryType||"expense");return}const del=e.target.closest("[data-delete-category]");if(del){openCategoryDelete(del.dataset.deleteCategory,del.dataset.categoryType||"expense");return}const add=e.target.closest("[data-add-category]");if(add){openCategoryEditor(null,add.dataset.addCategory,"planned",add.dataset.categoryType||"expense");return}const addSaving=e.target.closest("[data-add-saving]");if(addSaving)openModal("saving")});
function renameCategory(id,type,name){name=String(name||"").trim();if(!name)return;const map=type==="income"?(state.incomeCategoryNames=state.incomeCategoryNames||{}):(state.categoryNames=state.categoryNames||{});map[id]=name;const custom=type==="income"?state.customIncomeCategories:state.customExpenseCategories,found=custom.find(c=>c.id===id);if(found)found.name=name;const c=catById(id,type);if(c)c.name=name}
document.getElementById("closeCategoryEdit").addEventListener("click",closeCategoryEditor);categoryEditBackdrop.addEventListener("click",e=>{if(e.target===categoryEditBackdrop)closeCategoryEditor()});
saveCategoryEdit.addEventListener("click",()=>{const amount=Math.max(0,Math.round((Number(categoryBudgetInput.value)||0)*100)/100);let createdId=null;if(categoryEditMode==="planned"){const c=categoriesForType(categoryEditType).find(x=>x.id===categoryEditId);if(!c)return;const newName=categoryNameInput.value.trim();if(newName)renameCategory(c.id,categoryEditType,newName);setCategoryPlan(c.id,categoryEditType,amount,categoryEditOwner,categoryPlanScope)}else if(categoryEditMode==="actual"){const c=catById(categoryEditId,categoryEditType),label=c?.saving?"Ajustement épargne":"Ajustement manuel";setCategoryActual(categoryEditId,amount,categoryEditType,label)}else{const name=categoryNameInput.value.trim();if(!name)return categoryNameInput.focus();const createdFrom=monthKey(state.selectedMonth);if(categoryEditType==="income"){const c={id:`custom-income-${uid()}`,name,budget:amount,owner:categoryEditOwner,custom:true,createdFrom};createdId=c.id;INCOME_CATEGORIES.push(c);state.customIncomeCategories.push({...c});state.incomeBudgets[c.id]=amount;state.incomeCategoryOwners[c.id]=categoryEditOwner}else{const c={id:`custom-${uid()}`,name,budget:amount,section:categoryEditSection||"Vie courante",owner:categoryEditOwner,custom:true,createdFrom};createdId=c.id;EXPENSE_CATEGORIES.push(c);state.customExpenseCategories.push({...c});state.categoryBudgets[c.id]=amount;state.categoryOwners[c.id]=categoryEditOwner}}saveState();closeCategoryEditor();render();if(createdId&&categoryEditOrigin==="transaction")selectCreatedTransactionCategory(createdId)});

let categoryDeleteId=null,categoryDeleteType="expense";const categoryDeleteBackdrop=document.getElementById("categoryDeleteBackdrop"),categoryDeleteName=document.getElementById("categoryDeleteName"),categoryDeleteKind=document.getElementById("categoryDeleteKind");
function openCategoryDelete(id,type="expense"){const c=categoriesForType(type).find(x=>x.id===id);if(!c)return;categoryDeleteId=id;categoryDeleteType=type;categoryDeleteName.textContent=c.name;categoryDeleteKind.textContent=state.selectedMonth;categoryDeleteBackdrop.classList.add("open");categoryDeleteBackdrop.setAttribute("aria-hidden","false")}
function closeCategoryDelete(){categoryDeleteBackdrop.classList.remove("open");categoryDeleteBackdrop.setAttribute("aria-hidden","true");categoryDeleteId=null;categoryDeleteType="expense"}
function deleteCategoryForMonth(){if(!categoryDeleteId)return;const key=monthKey(state.selectedMonth),store=categoryDeleteType==="income"?(state.deletedIncomeCategoryMonths=state.deletedIncomeCategoryMonths||{}):(state.deletedCategoryMonths=state.deletedCategoryMonths||{});const list=new Set(store[key]||[]);list.add(categoryDeleteId);store[key]=[...list];saveState();closeCategoryDelete();render()}
function deleteCategoryForAllMonths(){if(!categoryDeleteId)return;const globalKey=categoryDeleteType==="income"?"deletedIncomeCategoriesGlobal":"deletedCategoriesGlobal",monthKeyName=categoryDeleteType==="income"?"deletedIncomeCategoryMonths":"deletedCategoryMonths";state[globalKey]=Array.isArray(state[globalKey])?state[globalKey]:[];if(!state[globalKey].includes(categoryDeleteId))state[globalKey].push(categoryDeleteId);Object.keys(state[monthKeyName]||{}).forEach(key=>{state[monthKeyName][key]=(state[monthKeyName][key]||[]).filter(id=>id!==categoryDeleteId);if(!state[monthKeyName][key].length)delete state[monthKeyName][key]});saveState();closeCategoryDelete();render()}
document.getElementById("closeCategoryDelete").addEventListener("click",closeCategoryDelete);document.getElementById("cancelCategoryDelete").addEventListener("click",closeCategoryDelete);document.getElementById("deleteCategoryMonth").addEventListener("click",deleteCategoryForMonth);document.getElementById("deleteCategoryAll").addEventListener("click",deleteCategoryForAllMonths);categoryDeleteBackdrop.addEventListener("click",e=>{if(e.target===categoryDeleteBackdrop)closeCategoryDelete()});
let modalType="expense",modalOwner="common",transactionScope="month";const backdrop=document.getElementById("modalBackdrop"),amountInput=document.getElementById("amountInput"),transactionLabelInput=document.getElementById("transactionLabel"),categorySelect=document.getElementById("categorySelect"),saveBtn=document.getElementById("saveTransaction"),ownerButtons=[...document.querySelectorAll("#ownerSwitch .owner-option")],transactionScopeField=document.getElementById("transactionScopeField"),transactionScopeHint=document.getElementById("transactionScopeHint"),transactionScopeButtons=[...document.querySelectorAll("[data-transaction-scope]")];buildCustomSelect(categorySelect);
function setModalOwner(owner){modalOwner=owner;ownerButtons.forEach(b=>b.classList.toggle("active",b.dataset.owner===owner))}
function setTransactionScope(scope){transactionScope=scope;transactionScopeButtons.forEach(b=>b.classList.toggle("active",b.dataset.transactionScope===scope));transactionScopeHint.textContent=scope==="forward"?`Cette opération sera reprise automatiquement à partir de ${state.selectedMonth}.`:`Cette opération sera comptée uniquement sur ${state.selectedMonth}.`}
function modalDataType(){return modalType==="saving"?"expense":modalType}
function categoryDefaultOwner(){const type=modalDataType(),c=catById(categorySelect.value,type);return c?planForCategory(c,state.selectedMonth,type).owner||"common":"common"}
function groupedExpenseOptions(cats){return ["Obligatoires","Abonnements","Vie courante"].map(s=>`<optgroup label="${s}">${cats.filter(c=>c.section===s).map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("")}</optgroup>`).join("")}
function populateTransactionCategories(selected=""){const isSaving=modalType==="saving",type=modalDataType(),cats=isSaving?visibleSavingCategories():type==="expense"?visibleExpenseCategories():visibleIncomeCategories(),placeholder=`<option value="" disabled>Choisir une catégorie</option>`,choices=type==="expense"?groupedExpenseOptions(cats):cats.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join(""),create=isSaving?"":`<optgroup label="Nouveau"><option value="__create__">＋ Créer un nouveau champ…</option></optgroup>`;categorySelect.innerHTML=placeholder+choices+create;categorySelect.value=selected&&[...categorySelect.options].some(o=>o.value===selected)?selected:"";rebuildCustomSelect(categorySelect);syncCustomSelect(categorySelect)}
function selectCreatedTransactionCategory(id){populateTransactionCategories(id);setModalOwner(categoryDefaultOwner());refreshAmountState();setTimeout(()=>amountInput.focus(),40)}
function openModal(type){modalType=type;const isSaving=type==="saving";document.getElementById("modalTitle").textContent=isSaving?"Ajouter une épargne":type==="expense"?"Ajouter une dépense":"Ajouter une rentrée";document.getElementById("modalKind").textContent=state.selectedMonth;saveBtn.className=`btn ${type==='expense'?'btn-expense':'btn-income'} save`;saveBtn.textContent=isSaving?"Ajouter l’épargne":type==="expense"?"Ajouter la dépense":"Ajouter la rentrée";populateTransactionCategories();setModalOwner("common");setTransactionScope("month");transactionScopeField.style.display=isSaving?"none":"block";amountInput.value="";transactionLabelInput.value="";saveBtn.disabled=true;backdrop.classList.add("open");backdrop.setAttribute("aria-hidden","false");setTimeout(()=>amountInput.focus(),80)}
function closeModal(){closeCustomSelects();backdrop.classList.remove("open");backdrop.setAttribute("aria-hidden","true")}
function refreshAmountState(){saveBtn.disabled=!(Number(amountInput.value)>0&&categorySelect.value&&categorySelect.value!=="__create__")}
function nudgeAmount(direction){if(direction>0)amountInput.stepUp();else amountInput.stepDown();refreshAmountState();amountInput.focus()}
document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>openModal(b.dataset.add)));document.getElementById("closeModal").addEventListener("click",closeModal);backdrop.addEventListener("click",e=>{if(e.target===backdrop)closeModal()});amountInput.addEventListener("input",refreshAmountState);document.getElementById("amountUp").addEventListener("click",()=>nudgeAmount(1));document.getElementById("amountDown").addEventListener("click",()=>nudgeAmount(-1));ownerButtons.forEach(b=>b.addEventListener("click",()=>setModalOwner(b.dataset.owner)));transactionScopeButtons.forEach(b=>b.addEventListener("click",()=>setTransactionScope(b.dataset.transactionScope)));categorySelect.addEventListener("change",()=>{if(categorySelect.value==="__create__"){categorySelect.value="";syncCustomSelect(categorySelect);refreshAmountState();openCategoryEditor(null,modalType==="expense"?"Vie courante":"Revenus","planned",modalDataType(),"transaction");return}setModalOwner(categoryDefaultOwner());refreshAmountState()});
function transactionDateForSelectedMonth(){const [y,m]=monthKey(state.selectedMonth).split("-");const now=new Date();const current=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const day=monthKey(state.selectedMonth)===current?String(now.getDate()).padStart(2,'0'):"01";return `${y}-${m}-${day}`}
saveBtn.addEventListener("click",()=>{const amount=Math.round(Number(amountInput.value)*100)/100;if(!(amount>0)||!categorySelect.value||categorySelect.value==="__create__")return;const recurring=modalType!=="saving"&&transactionScope==="forward",id=uid(),label=transactionLabelInput.value.trim();state.transactions.push({id,type:modalDataType(),category:categorySelect.value,owner:modalOwner,amount,date:transactionDateForSelectedMonth(),seed:false,...(label?{label}:{}),...(recurring?{scope:"forward",seriesId:id,excludedMonths:[],overrides:{}}:{})});saveState();closeModal();render()});
let undoTimer=null,undoAction=null;const undoToast=document.getElementById("undoToast"),undoToastText=document.getElementById("undoToastText"),undoToastBtn=document.getElementById("undoToastBtn");
function showUndoToast(label,action=null){undoAction=typeof action==="function"?action:null;undoToastText.textContent=label;undoToastBtn.style.display=undoAction?"":"none";undoToast.classList.add("show");clearTimeout(undoTimer);undoTimer=setTimeout(()=>{undoAction=null;undoToast.classList.remove("show")},6500)}
function removeTransactions(predicate,label){const removed=state.transactions.filter(predicate);if(!removed.length)return;state.transactions=state.transactions.filter(t=>!predicate(t));saveState();render();showUndoToast(label,()=>{state.transactions.push(...removed);saveState();render()})}
function transactionSnapshot(){return JSON.parse(JSON.stringify(state.transactions))}
function restoreTransactionSnapshot(snapshot){state.transactions=snapshot;saveState();render()}
undoToastBtn.addEventListener("click",()=>{if(!undoAction)return;const action=undoAction;undoAction=null;action();undoToast.classList.remove("show");clearTimeout(undoTimer)});
const recurrenceDeleteBackdrop=document.getElementById("recurrenceDeleteBackdrop"),recurrenceDeleteName=document.getElementById("recurrenceDeleteName"),recurrenceDeleteKind=document.getElementById("recurrenceDeleteKind");let recurrenceDeleteSourceId=null;
function openRecurrenceDelete(sourceId){const root=recurringRoot(sourceId);if(!root)return;const occurrence=transactionsForMonthKey(monthKey(state.selectedMonth)).find(t=>t.sourceId===sourceId)||root;recurrenceDeleteSourceId=sourceId;recurrenceDeleteName.textContent=transactionTitle(occurrence);recurrenceDeleteKind.textContent=state.selectedMonth;recurrenceDeleteBackdrop.classList.add("open");recurrenceDeleteBackdrop.setAttribute("aria-hidden","false")}
function closeRecurrenceDelete(){recurrenceDeleteBackdrop.classList.remove("open");recurrenceDeleteBackdrop.setAttribute("aria-hidden","true");recurrenceDeleteSourceId=null}
function mutateRecurringWithUndo(label,mutator){const snapshot=transactionSnapshot();mutator();saveState();render();showUndoToast(label,()=>restoreTransactionSnapshot(snapshot));closeRecurrenceDelete();closeRecurrenceEdit()}
function deleteRecurringMonth(sourceId,key){const root=recurringRoot(sourceId);if(!root)return;root.excludedMonths=Array.isArray(root.excludedMonths)?root.excludedMonths:[];if(!root.excludedMonths.includes(key))root.excludedMonths.push(key);if(root.overrides)delete root.overrides[key]}
function deleteRecurringForward(sourceId,key){const root=recurringRoot(sourceId);if(!root)return;const seriesId=recurringSeriesId(root),prev=previousMonthKey(key);state.transactions=state.transactions.filter(t=>{if(t.scope!=="forward"||recurringSeriesId(t)!==seriesId)return true;const start=String(t.date||"").slice(0,7);if(start>=key)return false;if(!t.endMonth||t.endMonth>=key)t.endMonth=prev;if(t.overrides)Object.keys(t.overrides).filter(k=>k>=key).forEach(k=>delete t.overrides[k]);if(Array.isArray(t.excludedMonths))t.excludedMonths=t.excludedMonths.filter(k=>k<key);return true})}
function deleteRecurringSeries(sourceId){const root=recurringRoot(sourceId);if(!root)return;const seriesId=recurringSeriesId(root);state.transactions=state.transactions.filter(t=>!(t.scope==="forward"&&recurringSeriesId(t)===seriesId))}
document.getElementById("closeRecurrenceDelete").addEventListener("click",closeRecurrenceDelete);document.getElementById("cancelRecurrenceDelete").addEventListener("click",closeRecurrenceDelete);recurrenceDeleteBackdrop.addEventListener("click",e=>{if(e.target===recurrenceDeleteBackdrop)closeRecurrenceDelete()});document.getElementById("deleteRecurrenceMonth").addEventListener("click",()=>{if(recurrenceDeleteSourceId)mutateRecurringWithUndo("Occurrence supprimée",()=>deleteRecurringMonth(recurrenceDeleteSourceId,monthKey(state.selectedMonth)))});document.getElementById("deleteRecurrenceForward").addEventListener("click",()=>{if(recurrenceDeleteSourceId)mutateRecurringWithUndo("Récurrence arrêtée",()=>deleteRecurringForward(recurrenceDeleteSourceId,monthKey(state.selectedMonth)))});document.getElementById("deleteRecurrenceAll").addEventListener("click",()=>{if(recurrenceDeleteSourceId)mutateRecurringWithUndo("Série supprimée",()=>deleteRecurringSeries(recurrenceDeleteSourceId))});

const recurrenceEditBackdrop=document.getElementById("recurrenceEditBackdrop"),recurrenceAmountInput=document.getElementById("recurrenceAmountInput"),recurrenceLabelInput=document.getElementById("recurrenceLabelInput"),recurrenceCategorySelect=document.getElementById("recurrenceCategorySelect"),recurrenceEditKind=document.getElementById("recurrenceEditKind"),recurrenceOwnerButtons=[...document.querySelectorAll("[data-recurrence-owner]")],recurrenceEditScopeButtons=[...document.querySelectorAll("[data-recurrence-edit-scope]")],recurrenceEditHint=document.getElementById("recurrenceEditHint");let recurrenceEditSourceId=null,recurrenceEditOwner="common",recurrenceEditScopeValue="month";buildCustomSelect(recurrenceCategorySelect);
function setRecurrenceEditOwner(owner){recurrenceEditOwner=owner;recurrenceOwnerButtons.forEach(b=>b.classList.toggle("active",b.dataset.recurrenceOwner===owner))}
function setRecurrenceEditScope(scope){recurrenceEditScopeValue=scope;recurrenceEditScopeButtons.forEach(b=>b.classList.toggle("active",b.dataset.recurrenceEditScope===scope));recurrenceEditHint.textContent=scope==="month"?`Seule l’occurrence de ${state.selectedMonth} sera modifiée.`:scope==="forward"?`Les mois précédents restent inchangés ; la nouvelle valeur s’applique à partir de ${state.selectedMonth}.`:`Toutes les occurrences de cette série, passées et futures, utiliseront ces valeurs.`}
function recurrenceCategoryOptions(type,currentId){let cats=type==="income"?visibleIncomeCategories():visibleExpenseCategories();const current=catById(currentId,type);if(current&&!cats.some(c=>c.id===current.id))cats=[categoryView(current,type),...cats];return type==="expense"?groupedExpenseOptions(cats):cats.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("")}
function openRecurrenceEdit(sourceId){const root=recurringRoot(sourceId);if(!root)return;const key=monthKey(state.selectedMonth),occurrence=transactionsForMonthKey(key).find(t=>t.sourceId===sourceId);if(!occurrence)return;recurrenceEditSourceId=sourceId;recurrenceEditKind.textContent=`${state.selectedMonth} · ${root.type==="income"?"Revenu":"Dépense"}`;recurrenceLabelInput.value=String(occurrence.label||"");recurrenceAmountInput.value=Number(occurrence.amount||0).toFixed(2);setRecurrenceEditOwner(transactionOwner(occurrence));recurrenceCategorySelect.innerHTML=recurrenceCategoryOptions(root.type,occurrence.category);recurrenceCategorySelect.value=occurrence.category;rebuildCustomSelect(recurrenceCategorySelect);syncCustomSelect(recurrenceCategorySelect);setRecurrenceEditScope("month");recurrenceEditBackdrop.classList.add("open");recurrenceEditBackdrop.setAttribute("aria-hidden","false");setTimeout(()=>recurrenceAmountInput.focus(),70)}
function closeRecurrenceEdit(){closeCustomSelects();recurrenceEditBackdrop.classList.remove("open");recurrenceEditBackdrop.setAttribute("aria-hidden","true");recurrenceEditSourceId=null}
function recurringChanges(){return {amount:Math.max(.01,Math.round((Number(recurrenceAmountInput.value)||0)*100)/100),owner:recurrenceEditOwner,category:recurrenceCategorySelect.value,label:recurrenceLabelInput.value.trim()}}
function modifyRecurringMonth(sourceId,key,changes){const root=recurringRoot(sourceId);if(!root)return;root.overrides=root.overrides&&typeof root.overrides==="object"?root.overrides:{};root.overrides[key]={amount:changes.amount,owner:changes.owner,category:changes.category,...(changes.label?{label:changes.label}:{label:""})};root.excludedMonths=(root.excludedMonths||[]).filter(k=>k!==key)}
function modifyRecurringForward(sourceId,key,changes){const root=recurringRoot(sourceId);if(!root)return;const seriesId=recurringSeriesId(root),prev=previousMonthKey(key),day=recurringOccurrenceDate(root,key).slice(8,10),type=root.type;state.transactions=state.transactions.filter(t=>{if(t.scope!=="forward"||recurringSeriesId(t)!==seriesId)return true;const start=String(t.date||"").slice(0,7);if(start>=key)return false;if(!t.endMonth||t.endMonth>=key)t.endMonth=prev;if(t.overrides)Object.keys(t.overrides).filter(k=>k>=key).forEach(k=>delete t.overrides[k]);if(Array.isArray(t.excludedMonths))t.excludedMonths=t.excludedMonths.filter(k=>k<key);return true});const id=uid();state.transactions.push({id,type,category:changes.category,owner:changes.owner,amount:changes.amount,date:`${key}-${day}`,seed:false,scope:"forward",seriesId,excludedMonths:[],overrides:{},...(changes.label?{label:changes.label}:{})})}
function modifyRecurringSeries(sourceId,changes){const roots=recurringSeriesRootsFromSource(sourceId);roots.forEach(root=>{root.amount=changes.amount;root.owner=changes.owner;root.category=changes.category;if(changes.label)root.label=changes.label;else delete root.label;root.overrides={}})}
recurrenceOwnerButtons.forEach(b=>b.addEventListener("click",()=>setRecurrenceEditOwner(b.dataset.recurrenceOwner)));recurrenceEditScopeButtons.forEach(b=>b.addEventListener("click",()=>setRecurrenceEditScope(b.dataset.recurrenceEditScope)));document.getElementById("closeRecurrenceEdit").addEventListener("click",closeRecurrenceEdit);recurrenceEditBackdrop.addEventListener("click",e=>{if(e.target===recurrenceEditBackdrop)closeRecurrenceEdit()});document.getElementById("saveRecurrenceEdit").addEventListener("click",()=>{if(!recurrenceEditSourceId||!(Number(recurrenceAmountInput.value)>0)||!recurrenceCategorySelect.value)return;const sourceId=recurrenceEditSourceId,key=monthKey(state.selectedMonth),changes=recurringChanges();mutateRecurringWithUndo("Récurrence modifiée",()=>{if(recurrenceEditScopeValue==="month")modifyRecurringMonth(sourceId,key,changes);else if(recurrenceEditScopeValue==="forward")modifyRecurringForward(sourceId,key,changes);else modifyRecurringSeries(sourceId,changes)})});

document.getElementById("historyList").addEventListener("click",e=>{const toggle=e.target.closest("[data-toggle-group]");if(toggle){document.querySelector(`[data-history-group="${toggle.dataset.toggleGroup}"]`)?.classList.toggle("open");return}const group=e.target.closest("[data-delete-group]");if(group){const id=group.dataset.deleteGroup;removeTransactions(t=>t.bulkGroupId===id,"Mise à jour groupée supprimée");return}const editRecurring=e.target.closest("[data-edit-recurring]");if(editRecurring){openRecurrenceEdit(editRecurring.dataset.editRecurring);return}const deleteRecurring=e.target.closest("[data-delete-recurring]");if(deleteRecurring){openRecurrenceDelete(deleteRecurring.dataset.deleteRecurring);return}const del=e.target.closest("[data-delete]");if(del){removeTransactions(t=>t.id===del.dataset.delete,"Opération supprimée");return}});

const settingsBackdrop=document.getElementById("settingsBackdrop");function openSettings(){settingsBackdrop.classList.add("open");settingsBackdrop.setAttribute("aria-hidden","false")}function closeSettings(){settingsBackdrop.classList.remove("open");settingsBackdrop.setAttribute("aria-hidden","true")}document.getElementById("settingsBtn").addEventListener("click",openSettings);document.getElementById("closeSettings").addEventListener("click",closeSettings);settingsBackdrop.addEventListener("click",e=>{if(e.target===settingsBackdrop)closeSettings()});

document.getElementById("exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify({app:"Budget foyer",version:3,exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`budget-foyer-${monthKey(state.selectedMonth)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
const importFile=document.getElementById("importFile");document.getElementById("importBtn").addEventListener("click",()=>importFile.click());importFile.addEventListener("change",async()=>{const file=importFile.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()),candidate=parsed?.state||parsed;if(!candidate||!Array.isArray(candidate.transactions))throw new Error("format");if(!confirm("Importer cette sauvegarde et remplacer les données locales actuelles ?")){importFile.value="";return}localStorage.setItem(STORAGE_KEY,JSON.stringify(candidate));state=loadState();applyCategoryState();ensureMonthAvailable(state.selectedMonth);MONTHS.forEach(label=>{if(![...monthSelect.options].some(o=>o.value===label)){const o=document.createElement("option");o.value=label;o.textContent=label;monthSelect.appendChild(o)}});rebuildCustomSelect(monthSelect);monthSelect.value=state.selectedMonth;syncCustomSelect(monthSelect);updateMonthNav();render();showUndoToast("Sauvegarde importée")}catch{alert("Ce fichier n’est pas une sauvegarde valide de Budget foyer.")}finally{importFile.value=""}});
document.getElementById("resetBtn").addEventListener("click",()=>{if(confirm("Réinitialiser toutes les données avec la base de septembre 2026 ? Cette action efface les modifications locales.")){state=seedState();applyCategoryState();saveState();monthSelect.value=state.selectedMonth;syncCustomSelect(monthSelect);updateMonthNav();render();closeSettings()}});

let trackingYear=Number(monthKey(state.selectedMonth).slice(0,4));
function labelsForYear(year){return Array.from({length:12},(_,i)=>labelFromYM(year,i+1))}
function hasMonthActivity(m){return m.tx.length>0||m.plannedIncome>0||m.plannedExpense>0||m.plannedSaving>0}
function annualMetrics(year){
 const months=labelsForYear(year).map(label=>metricsForMonth(label));
 const active=months.filter(hasMonthActivity);
 const total=prop=>sum(months.map(m=>Number(m[prop])||0));
 return {
  year,months,active,
  income:total("income"),expense:total("expense"),saving:total("saving"),balance:total("balance"),
  plannedIncome:total("plannedIncome"),plannedExpense:total("plannedExpense"),plannedSaving:total("plannedSaving"),plannedBalance:total("plannedBalance"),
  incomeB:total("incomeB"),incomeA:total("incomeA"),expenseB:total("expenseB"),expenseA:total("expenseA"),
  savingB:total("savingBShare"),savingA:total("savingAShare"),restB:total("restB"),restA:total("restA")
 }
}
function formatSignedEuro(v){return `${v>0.005?"+":""}${euro(v)}`}
function trendClass(v,positiveIsGood=true){if(Math.abs(v)<.005)return"neutral";const good=positiveIsGood?v>0:v<0;return good?"positive":"negative"}
function monthShort(label){return label.split(" ")[0].slice(0,4).replace("é","e").replace("û","u")}
function renderTrackingChart(months){
 const host=document.getElementById("trackingChart");if(!host)return;
 const values=months.flatMap(m=>[m.balance,m.plannedBalance]),max=Math.max(1,...values.map(v=>Math.abs(Number(v)||0)));
 const W=900,H=270,pad={l:54,r:18,t:18,b:42},innerW=W-pad.l-pad.r,innerH=H-pad.t-pad.b,zeroY=pad.t+innerH/2,scale=(innerH/2-12)/max;
 const x=i=>pad.l+(innerW*(i/(months.length-1||1))),y=v=>zeroY-(Number(v)||0)*scale;
 const real=months.map((m,i)=>`${x(i)},${y(m.balance)}`).join(" "),planned=months.map((m,i)=>`${x(i)},${y(m.plannedBalance)}`).join(" ");
 const grid=[-1,-.5,0,.5,1].map(f=>{const yy=zeroY-f*(innerH/2-12),val=f*max;return `<line class="${f===0?"chart-zero-line":"chart-grid-line"}" x1="${pad.l}" x2="${W-pad.r}" y1="${yy}" y2="${yy}"/><text class="chart-axis-label" x="${pad.l-8}" y="${yy+3}" text-anchor="end">${Math.round(val)} €</text>`}).join("");
 const labels=months.map((m,i)=>`<text class="chart-month-label" x="${x(i)}" y="${H-12}" text-anchor="middle">${monthShort(m.label)}</text>`).join("");
 const realPts=months.map((m,i)=>`<circle class="chart-real-point" cx="${x(i)}" cy="${y(m.balance)}" r="4"><title>${m.label} · Réel ${euro(m.balance)}</title></circle>`).join("");
 const plannedPts=months.map((m,i)=>`<circle class="chart-planned-point" cx="${x(i)}" cy="${y(m.plannedBalance)}" r="3"><title>${m.label} · Prévu ${euro(m.plannedBalance)}</title></circle>`).join("");
 host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Évolution du reste mensuel réel et prévu"><g>${grid}</g><polyline class="chart-planned-line" points="${planned}"/><polyline class="chart-real-line" points="${real}"/>${plannedPts}${realPts}${labels}</svg>`;
}
function renderTracking(){
 const yearEl=document.getElementById("trackingYear");if(!yearEl)return;
 const a=annualMetrics(trackingYear),activeCount=Math.max(1,a.active.length);
 yearEl.textContent=String(trackingYear);
 document.getElementById("yearIncome").textContent=euro(a.income);
 document.getElementById("yearExpense").textContent=euro(a.expense);
 document.getElementById("yearSaving").textContent=euro(a.saving);
 document.getElementById("yearBalance").textContent=euro(a.balance);
 document.getElementById("yearIncomeDelta").textContent=`Prévu ${euro(a.plannedIncome)}`;
 document.getElementById("yearExpenseDelta").textContent=`Prévu ${euro(a.plannedExpense)}`;
 document.getElementById("yearSavingDelta").textContent=`Prévu ${euro(a.plannedSaving)}`;
 document.getElementById("yearBalanceAverage").textContent=`Moyenne ${euro(a.balance/activeCount)} / mois actif`;
 document.getElementById("yearRestB").textContent=euro(a.restB);
 document.getElementById("yearRestA").textContent=euro(a.restA);
 document.getElementById("yearPersonBDetail").textContent=`${euro(a.incomeB)} de revenus · ${euro(a.expenseB)} dépensés · ${euro(a.savingB)} épargnés`;
 document.getElementById("yearPersonADetail").textContent=`${euro(a.incomeA)} de revenus · ${euro(a.expenseA)} dépensés · ${euro(a.savingA)} épargnés`;
 const currentKey=monthKey(state.selectedMonth);
 document.getElementById("trackingMonths").innerHTML=a.months.map((m,i)=>{
   const prev=i>0?a.months[i-1]:metricsForMonth(labelFromYM(trackingYear-1,12)),delta=m.balance-prev.balance,trend=trendClass(delta,true),empty=!hasMonthActivity(m);
   return `<div class="tracking-month-row ${empty?"empty":""} ${m.key===currentKey?"current":""}">
     <span class="month-name">${m.label}</span>
     <span class="money">${euro(m.income)}</span>
     <span class="money">${euro(m.expense)}</span>
     <span class="money">${euro(m.saving)}</span>
     <span class="money">${euro(m.balance)}</span>
     <span class="trend ${trend}">${Math.abs(delta)<.005?"0 €":formatSignedEuro(delta)}</span>
     <div class="month-main" style="display:none"><span>Reste du mois</span><strong>${euro(m.balance)}</strong></div>
     <div class="month-sub"><span>Revenus ${euro(m.income)}</span><span>Dépenses ${euro(m.expense)}</span><span>Épargne ${euro(m.saving)}</span></div>
   </div>`
 }).join("");
 renderTrackingChart(a.months);
}
document.getElementById("prevYear")?.addEventListener("click",()=>{trackingYear--;renderTracking()});
document.getElementById("nextYear")?.addEventListener("click",()=>{trackingYear++;renderTracking()});

document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closeCategoryEditor();closeCategoryDelete();closeRecurrenceDelete();closeRecurrenceEdit();closeSettings()}});
render();
