// V2.3 — opérations, récurrences et actions d'historique
let modalType="expense",modalOwner="common",transactionScope="month",editingTransactionId=null;const backdrop=document.getElementById("modalBackdrop"),amountInput=document.getElementById("amountInput"),transactionLabelInput=document.getElementById("transactionLabel"),categorySelect=document.getElementById("categorySelect"),saveBtn=document.getElementById("saveTransaction"),ownerButtons=[...document.querySelectorAll("#ownerSwitch .owner-option")],transactionScopeField=document.getElementById("transactionScopeField"),transactionScopeHint=document.getElementById("transactionScopeHint"),transactionScopeButtons=[...document.querySelectorAll("[data-transaction-scope]")];buildCustomSelect(categorySelect);
function setModalOwner(owner){if(householdIsSolo())owner="B";modalOwner=owner;ownerButtons.forEach(b=>b.classList.toggle("active",b.dataset.owner===owner))}
function setTransactionScope(scope){transactionScope=scope;transactionScopeButtons.forEach(b=>b.classList.toggle("active",b.dataset.transactionScope===scope));transactionScopeHint.textContent=scope==="forward"?`Cette opération sera reprise automatiquement à partir de ${state.selectedMonth}.`:`Cette opération sera comptée uniquement sur ${state.selectedMonth}.`}
function modalDataType(){return modalType==="saving"?"expense":modalType}
function categoryDefaultOwner(){const type=modalDataType(),c=catById(categorySelect.value,type);return c?planForCategory(c,state.selectedMonth,type).owner||"common":"common"}
function groupedExpenseOptions(cats){return ["Obligatoires","Abonnements","Vie courante"].map(s=>`<optgroup label="${s}">${cats.filter(c=>c.section===s).map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("")}</optgroup>`).join("")}
function populateTransactionCategories(selected=""){
 const isSaving=modalType==="saving",type=modalDataType(),cats=isSaving?visibleSavingCategories():type==="expense"?visibleExpenseCategories():visibleIncomeCategories();
 const placeholder=`<option value="" disabled>Choisir une catégorie</option>`;
 let choices=isSaving?cats.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join(""):type==="expense"?groupedExpenseOptions(cats):cats.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("");
 if(selected&&!cats.some(c=>c.id===selected)){
   const archived=catById(selected,type);
   if(archived&&(!isSaving||archived.saving))choices+=`<optgroup label="Archivée"><option value="${escapeHtml(archived.id)}">${escapeHtml(archived.name)} · archivée</option></optgroup>`;
 }
 const create=`<optgroup label="Nouveau"><option value="__create__">＋ ${isSaving?"Créer une nouvelle épargne":"Créer un nouveau champ"}…</option></optgroup>`;
 categorySelect.innerHTML=placeholder+choices+create;
 categorySelect.value=selected&&[...categorySelect.options].some(o=>o.value===selected)?selected:"";
 rebuildCustomSelect(categorySelect);syncCustomSelect(categorySelect)
}
function selectCreatedTransactionCategory(id){populateTransactionCategories(id);setModalOwner(categoryDefaultOwner());refreshAmountState();setTimeout(()=>amountInput.focus(),40)}
function openModal(type,transaction=null){
 modalType=type;editingTransactionId=transaction?.id||null;const isSaving=type==="saving",editing=!!transaction;
 document.getElementById("modalTitle").textContent=editing?(isSaving?"Modifier l’épargne":type==="expense"?"Modifier la dépense":"Modifier la rentrée"):(isSaving?"Ajouter une épargne":type==="expense"?"Ajouter une dépense":"Ajouter une rentrée");
 document.getElementById("modalKind").textContent=state.selectedMonth;const ownerSwitchLabel=document.getElementById("ownerSwitchLabel");if(ownerSwitchLabel)ownerSwitchLabel.textContent=isSaving?"ÉPARGNÉ PAR ?":type==="expense"?"QUI A PAYÉ ?":"REÇU PAR ?";saveBtn.className=`btn ${type==='expense'?'btn-expense':'btn-income'} save`;saveBtn.textContent=editing?"Enregistrer":isSaving?"Ajouter l’épargne":type==="expense"?"Ajouter la dépense":"Ajouter la rentrée";
 populateTransactionCategories(transaction?.category||"");setModalOwner(transaction?.owner||categoryDefaultOwner()||"common");setTransactionScope(transaction?.scope==="forward"?"forward":"month");transactionScopeField.style.display=isSaving?"none":"block";
 amountInput.value=transaction?String(Number(transaction.amount)||""):"";transactionLabelInput.value=transaction?.label||"";refreshAmountState();backdrop.classList.add("open");backdrop.setAttribute("aria-hidden","false");setTimeout(()=>amountInput.focus(),80)
}
function closeModal(){closeCustomSelects();backdrop.classList.remove("open");backdrop.setAttribute("aria-hidden","true");editingTransactionId=null}
function refreshAmountState(){saveBtn.disabled=!(Number(amountInput.value)>0&&categorySelect.value&&categorySelect.value!=="__create__")}
function nudgeAmount(direction){if(direction>0)amountInput.stepUp();else amountInput.stepDown();refreshAmountState();amountInput.focus()}
document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>openModal(b.dataset.add)));document.getElementById("closeModal").addEventListener("click",closeModal);backdrop.addEventListener("click",e=>{if(e.target===backdrop)closeModal()});amountInput.addEventListener("input",refreshAmountState);document.getElementById("amountUp").addEventListener("click",()=>nudgeAmount(1));document.getElementById("amountDown").addEventListener("click",()=>nudgeAmount(-1));ownerButtons.forEach(b=>b.addEventListener("click",()=>setModalOwner(b.dataset.owner)));transactionScopeButtons.forEach(b=>b.addEventListener("click",()=>setTransactionScope(b.dataset.transactionScope)));categorySelect.addEventListener("change",()=>{if(categorySelect.value==="__create__"){categorySelect.value="";syncCustomSelect(categorySelect);refreshAmountState();openCategoryEditor(null,modalType==="saving"?"__savings__":modalType==="expense"?"Vie courante":"Revenus","planned",modalDataType(),"transaction");return}setModalOwner(categoryDefaultOwner());refreshAmountState()});
function transactionDateForSelectedMonth(){const [y,m]=monthKey(state.selectedMonth).split("-");const now=new Date();const current=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const day=monthKey(state.selectedMonth)===current?String(now.getDate()).padStart(2,'0'):"01";return `${y}-${m}-${day}`}
saveBtn.addEventListener("click",()=>{const amount=Math.round(Number(amountInput.value)*100)/100;if(!(amount>0)||!categorySelect.value||categorySelect.value==="__create__")return;const recurring=modalType!=="saving"&&transactionScope==="forward",label=transactionLabelInput.value.trim();
 if(editingTransactionId){const index=state.transactions.findIndex(t=>t.id===editingTransactionId);if(index<0)return;const previous=state.transactions[index],next={...previous,type:modalDataType(),category:categorySelect.value,owner:modalOwner,amount};if(label)next.label=label;else delete next.label;if(recurring){next.scope="forward";next.seriesId=next.seriesId||next.id;next.excludedMonths=Array.isArray(next.excludedMonths)?next.excludedMonths:[];next.overrides=next.overrides&&typeof next.overrides==="object"?next.overrides:{}}else{delete next.scope;delete next.seriesId;delete next.excludedMonths;delete next.overrides;delete next.endMonth}state.transactions[index]=next;
 }else{const id=uid();state.transactions.push({id,type:modalDataType(),category:categorySelect.value,owner:modalOwner,amount,date:transactionDateForSelectedMonth(),seed:false,...(label?{label}:{}),...(recurring?{scope:"forward",seriesId:id,excludedMonths:[],overrides:{}}:{})})}
 saveState();closeModal();render()});
let undoTimer=null,undoAction=null,transactionDeleteUndoBatch=null;const undoToast=document.getElementById("undoToast"),undoToastText=document.getElementById("undoToastText"),undoToastBtn=document.getElementById("undoToastBtn");
function showUndoToast(label,action=null,options={}){
 const keepDeleteBatch=!!options.keepDeleteBatch,duration=Number(options.duration)||9000;
 if(!keepDeleteBatch)transactionDeleteUndoBatch=null;
 undoAction=typeof action==="function"?action:null;
 undoToastText.textContent=label;
 undoToastBtn.style.display=undoAction?"":"none";
 undoToastBtn.textContent=options.buttonLabel||(undoAction?"Annuler":"");
 undoToast.classList.add("show");
 clearTimeout(undoTimer);
 undoTimer=setTimeout(()=>{undoAction=null;transactionDeleteUndoBatch=null;undoToast.classList.remove("show")},duration);
}
function restoreDeletedTransactionBatch(batch){
 if(!batch?.items?.length)return;
 const existing=new Set(state.transactions.map(t=>t.id));
 batch.items.forEach(item=>{if(!existing.has(item.id))state.transactions.push(cloneData(item))});
 transactionDeleteUndoBatch=null;
 saveState();
 render();
}
function removeTransactions(predicate,label){
 const removed=state.transactions.filter(predicate);
 if(!removed.length)return;
 if(!transactionDeleteUndoBatch)transactionDeleteUndoBatch={items:[],actions:0};
 const known=new Set(transactionDeleteUndoBatch.items.map(item=>item.id));
 removed.forEach(item=>{if(!known.has(item.id)){transactionDeleteUndoBatch.items.push(cloneData(item));known.add(item.id)}});
 transactionDeleteUndoBatch.actions++;
 state.transactions=state.transactions.filter(t=>!predicate(t));
 saveState();
 render();
 const batch=transactionDeleteUndoBatch,count=batch.items.length;
 const text=count===1&&batch.actions===1?label:`${count} opération${count>1?"s":""} supprimée${count>1?"s":""}`;
 showUndoToast(text,()=>restoreDeletedTransactionBatch(batch),{keepDeleteBatch:true,duration:10000,buttonLabel:count>1?"Annuler tout":"Annuler"});
}
function transactionSnapshot(){return JSON.parse(JSON.stringify(state.transactions))}
function restoreTransactionSnapshot(snapshot){state.transactions=snapshot;saveState();render()}
undoToastBtn.addEventListener("click",()=>{if(!undoAction)return;const action=undoAction;undoAction=null;action();transactionDeleteUndoBatch=null;undoToast.classList.remove("show");clearTimeout(undoTimer)});
const recurrenceDeleteBackdrop=document.getElementById("recurrenceDeleteBackdrop"),recurrenceDeleteName=document.getElementById("recurrenceDeleteName"),recurrenceDeleteKind=document.getElementById("recurrenceDeleteKind");let recurrenceDeleteSourceId=null;
function openRecurrenceDelete(sourceId){const root=recurringRoot(sourceId);if(!root)return;const occurrence=transactionsForMonthKey(monthKey(state.selectedMonth)).find(t=>t.sourceId===sourceId)||root;recurrenceDeleteSourceId=sourceId;recurrenceDeleteName.textContent=transactionTitle(occurrence);recurrenceDeleteKind.textContent=state.selectedMonth;recurrenceDeleteBackdrop.classList.add("open");recurrenceDeleteBackdrop.setAttribute("aria-hidden","false")}
function closeRecurrenceDelete(){recurrenceDeleteBackdrop.classList.remove("open");recurrenceDeleteBackdrop.setAttribute("aria-hidden","true");recurrenceDeleteSourceId=null}
function mutateRecurringWithUndo(label,mutator){const snapshot=transactionSnapshot();mutator();saveState();render();showUndoToast(label,()=>restoreTransactionSnapshot(snapshot));closeRecurrenceDelete();closeRecurrenceEdit()}
function deleteRecurringMonth(sourceId,key){const root=recurringRoot(sourceId);if(!root)return;root.excludedMonths=Array.isArray(root.excludedMonths)?root.excludedMonths:[];if(!root.excludedMonths.includes(key))root.excludedMonths.push(key);if(root.overrides)delete root.overrides[key]}
function deleteRecurringForward(sourceId,key){const root=recurringRoot(sourceId);if(!root)return;const seriesId=recurringSeriesId(root),prev=previousMonthKey(key);state.transactions=state.transactions.filter(t=>{if(t.scope!=="forward"||recurringSeriesId(t)!==seriesId)return true;const start=String(t.date||"").slice(0,7);if(start>=key)return false;if(!t.endMonth||t.endMonth>=key)t.endMonth=prev;if(t.overrides)Object.keys(t.overrides).filter(k=>k>=key).forEach(k=>delete t.overrides[k]);if(Array.isArray(t.excludedMonths))t.excludedMonths=t.excludedMonths.filter(k=>k<key);return true})}
function deleteRecurringSeries(sourceId){const root=recurringRoot(sourceId);if(!root)return;const seriesId=recurringSeriesId(root);state.transactions=state.transactions.filter(t=>!(t.scope==="forward"&&recurringSeriesId(t)===seriesId))}
document.getElementById("closeRecurrenceDelete").addEventListener("click",closeRecurrenceDelete);document.getElementById("cancelRecurrenceDelete").addEventListener("click",closeRecurrenceDelete);recurrenceDeleteBackdrop.addEventListener("click",e=>{if(e.target===recurrenceDeleteBackdrop)closeRecurrenceDelete()});document.getElementById("deleteRecurrenceMonth").addEventListener("click",()=>{if(recurrenceDeleteSourceId)mutateRecurringWithUndo("Occurrence supprimée",()=>deleteRecurringMonth(recurrenceDeleteSourceId,monthKey(state.selectedMonth)))});document.getElementById("deleteRecurrenceForward").addEventListener("click",()=>{if(recurrenceDeleteSourceId)mutateRecurringWithUndo("Récurrence arrêtée",()=>deleteRecurringForward(recurrenceDeleteSourceId,monthKey(state.selectedMonth)))});document.getElementById("deleteRecurrenceAll").addEventListener("click",()=>{if(recurrenceDeleteSourceId)mutateRecurringWithUndo("Série supprimée",()=>deleteRecurringSeries(recurrenceDeleteSourceId))});

const recurrenceEditBackdrop=document.getElementById("recurrenceEditBackdrop"),recurrenceAmountInput=document.getElementById("recurrenceAmountInput"),recurrenceLabelInput=document.getElementById("recurrenceLabelInput"),recurrenceCategorySelect=document.getElementById("recurrenceCategorySelect"),recurrenceEditKind=document.getElementById("recurrenceEditKind"),recurrenceOwnerButtons=[...document.querySelectorAll("[data-recurrence-owner]")],recurrenceEditScopeButtons=[...document.querySelectorAll("[data-recurrence-edit-scope]")],recurrenceEditHint=document.getElementById("recurrenceEditHint");let recurrenceEditSourceId=null,recurrenceEditOwner="common",recurrenceEditScopeValue="month";buildCustomSelect(recurrenceCategorySelect);
function setRecurrenceEditOwner(owner){if(householdIsSolo())owner="B";recurrenceEditOwner=owner;recurrenceOwnerButtons.forEach(b=>b.classList.toggle("active",b.dataset.recurrenceOwner===owner))}
function setRecurrenceEditScope(scope){recurrenceEditScopeValue=scope;recurrenceEditScopeButtons.forEach(b=>b.classList.toggle("active",b.dataset.recurrenceEditScope===scope));recurrenceEditHint.textContent=scope==="month"?`Seule l’occurrence de ${state.selectedMonth} sera modifiée.`:scope==="forward"?`Les mois précédents restent inchangés ; la nouvelle valeur s’applique à partir de ${state.selectedMonth}.`:`Toutes les occurrences de cette série, passées et futures, utiliseront ces valeurs.`}
function recurrenceCategoryOptions(type,currentId){let cats=type==="income"?visibleIncomeCategories():visibleExpenseCategories();const current=catById(currentId,type);if(current&&!cats.some(c=>c.id===current.id))cats=[categoryView(current,type),...cats];return type==="expense"?groupedExpenseOptions(cats):cats.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("")}
function openRecurrenceEdit(sourceId){const root=recurringRoot(sourceId);if(!root)return;const key=monthKey(state.selectedMonth),occurrence=transactionsForMonthKey(key).find(t=>t.sourceId===sourceId);if(!occurrence)return;recurrenceEditSourceId=sourceId;recurrenceEditKind.textContent=`${state.selectedMonth} · ${root.type==="income"?"Revenu":"Dépense"}`;recurrenceLabelInput.value=String(occurrence.label||"");recurrenceAmountInput.value=Number(occurrence.amount||0).toFixed(2);setRecurrenceEditOwner(transactionOwner(occurrence));recurrenceCategorySelect.innerHTML=recurrenceCategoryOptions(root.type,occurrence.category);recurrenceCategorySelect.value=occurrence.category;rebuildCustomSelect(recurrenceCategorySelect);syncCustomSelect(recurrenceCategorySelect);setRecurrenceEditScope("month");recurrenceEditBackdrop.classList.add("open");recurrenceEditBackdrop.setAttribute("aria-hidden","false");setTimeout(()=>recurrenceAmountInput.focus(),70)}
function closeRecurrenceEdit(){closeCustomSelects();recurrenceEditBackdrop.classList.remove("open");recurrenceEditBackdrop.setAttribute("aria-hidden","true");recurrenceEditSourceId=null}
function recurringChanges(){return {amount:Math.max(.01,Math.round((Number(recurrenceAmountInput.value)||0)*100)/100),owner:recurrenceEditOwner,category:recurrenceCategorySelect.value,label:recurrenceLabelInput.value.trim()}}
function modifyRecurringMonth(sourceId,key,changes){const root=recurringRoot(sourceId);if(!root)return;root.overrides=root.overrides&&typeof root.overrides==="object"?root.overrides:{};root.overrides[key]={amount:changes.amount,owner:changes.owner,category:changes.category,...(changes.label?{label:changes.label}:{label:""})};root.excludedMonths=(root.excludedMonths||[]).filter(k=>k!==key)}
function modifyRecurringForward(sourceId,key,changes){const root=recurringRoot(sourceId);if(!root)return;const seriesId=recurringSeriesId(root),prev=previousMonthKey(key),day=recurringOccurrenceDate(root,key).slice(8,10),type=root.type;state.transactions=state.transactions.filter(t=>{if(t.scope!=="forward"||recurringSeriesId(t)!==seriesId)return true;const start=String(t.date||"").slice(0,7);if(start>=key)return false;if(!t.endMonth||t.endMonth>=key)t.endMonth=prev;if(t.overrides)Object.keys(t.overrides).filter(k=>k>=key).forEach(k=>delete t.overrides[k]);if(Array.isArray(t.excludedMonths))t.excludedMonths=t.excludedMonths.filter(k=>k<key);return true});const id=uid();state.transactions.push({id,type,category:changes.category,owner:changes.owner,amount:changes.amount,date:`${key}-${day}`,seed:false,scope:"forward",seriesId,excludedMonths:[],overrides:{},...(changes.label?{label:changes.label}:{})})}
function modifyRecurringSeries(sourceId,changes){const roots=recurringSeriesRootsFromSource(sourceId);roots.forEach(root=>{root.amount=changes.amount;root.owner=changes.owner;root.category=changes.category;if(changes.label)root.label=changes.label;else delete root.label;root.overrides={}})}
recurrenceOwnerButtons.forEach(b=>b.addEventListener("click",()=>setRecurrenceEditOwner(b.dataset.recurrenceOwner)));recurrenceEditScopeButtons.forEach(b=>b.addEventListener("click",()=>setRecurrenceEditScope(b.dataset.recurrenceEditScope)));document.getElementById("closeRecurrenceEdit").addEventListener("click",closeRecurrenceEdit);recurrenceEditBackdrop.addEventListener("click",e=>{if(e.target===recurrenceEditBackdrop)closeRecurrenceEdit()});document.getElementById("saveRecurrenceEdit").addEventListener("click",()=>{if(!recurrenceEditSourceId||!(Number(recurrenceAmountInput.value)>0)||!recurrenceCategorySelect.value)return;const sourceId=recurrenceEditSourceId,key=monthKey(state.selectedMonth),changes=recurringChanges();mutateRecurringWithUndo("Récurrence modifiée",()=>{if(recurrenceEditScopeValue==="month")modifyRecurringMonth(sourceId,key,changes);else if(recurrenceEditScopeValue==="forward")modifyRecurringForward(sourceId,key,changes);else modifyRecurringSeries(sourceId,changes)})});

document.getElementById("historyList").addEventListener("click",e=>{const toggle=e.target.closest("[data-toggle-group]");if(toggle){document.querySelector(`[data-history-group="${toggle.dataset.toggleGroup}"]`)?.classList.toggle("open");return}const group=e.target.closest("[data-delete-group]");if(group){const id=group.dataset.deleteGroup;removeTransactions(t=>t.bulkGroupId===id,"Mise à jour groupée supprimée");return}const editRecurring=e.target.closest("[data-edit-recurring]");if(editRecurring){openRecurrenceEdit(editRecurring.dataset.editRecurring);return}const deleteRecurring=e.target.closest("[data-delete-recurring]");if(deleteRecurring){openRecurrenceDelete(deleteRecurring.dataset.deleteRecurring);return}const editTx=e.target.closest("[data-edit-transaction]");if(editTx){const t=state.transactions.find(x=>x.id===editTx.dataset.editTransaction);if(t){const saving=t.type==="expense"&&catById(t.category,"expense")?.saving;openModal(saving?"saving":t.type,t)}return}const del=e.target.closest("[data-delete]");if(del){removeTransactions(t=>t.id===del.dataset.delete,"Opération supprimée");return}});
