// V2.2 — gestion des catégories et budgets
const categoryGrid=document.getElementById("categoryGrid"),categoryEditBackdrop=document.getElementById("categoryEditBackdrop"),categoryEditTitle=document.getElementById("categoryEditTitle"),categoryEditKind=document.getElementById("categoryEditKind"),categoryNameField=document.getElementById("categoryNameField"),categoryNameInput=document.getElementById("categoryNameInput"),categorySectionField=document.getElementById("categorySectionField"),categorySectionButtons=[...document.querySelectorAll("[data-category-section]")],categoryOwnerField=document.getElementById("categoryOwnerField"),categoryOwnerLabel=document.getElementById("categoryOwnerLabel"),categoryOwnerButtons=[...document.querySelectorAll("[data-category-owner]")],categoryBudgetInput=document.getElementById("categoryBudgetInput"),categoryAmountLabel=document.getElementById("categoryAmountLabel"),categoryPlanScopeField=document.getElementById("categoryPlanScopeField"),categoryPlanScopeButtons=[...document.querySelectorAll("[data-plan-scope]")],categoryPlanScopeHint=document.getElementById("categoryPlanScopeHint"),saveCategoryEdit=document.getElementById("saveCategoryEdit");
let categoryEditMode="planned",categoryEditId=null,categoryEditSection=null,categoryEditType="expense",categoryEditOwner="common",categoryPlanScope="forward",categoryEditOrigin="categories";
function setCategoryEditOwner(owner){categoryEditOwner=owner;categoryOwnerButtons.forEach(b=>b.classList.toggle("active",b.dataset.categoryOwner===owner))}
function setCategoryEditSection(section){categoryEditSection=section;categorySectionButtons.forEach(b=>b.classList.toggle("active",b.dataset.categorySection===section))}
function setCategoryPlanScope(scope){categoryPlanScope=scope;categoryPlanScopeButtons.forEach(b=>b.classList.toggle("active",b.dataset.planScope===scope));categoryPlanScopeHint.textContent=scope==="month"?`Ce changement concerne uniquement ${state.selectedMonth}.`:`Le nouveau prévu s'appliquera à ${state.selectedMonth} et aux mois suivants.`}
categoryOwnerButtons.forEach(b=>b.addEventListener("click",()=>setCategoryEditOwner(b.dataset.categoryOwner)));categorySectionButtons.forEach(b=>b.addEventListener("click",()=>setCategoryEditSection(b.dataset.categorySection)));categoryPlanScopeButtons.forEach(b=>b.addEventListener("click",()=>setCategoryPlanScope(b.dataset.planScope)));
function categoriesForType(type){return type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES}
function openCategoryEditor(id=null,section=null,mode="planned",type="expense",origin="categories"){
 closeCustomSelects();categoryEditId=id;categoryEditSection=section;categoryEditMode=id?mode:"add";categoryEditType=type;categoryEditOrigin=origin;const ownerEditable=categoryEditMode==="add"||categoryEditMode==="planned";categoryOwnerField.style.display=ownerEditable?"block":"none";categoryPlanScopeField.style.display=categoryEditMode==="planned"?"block":"none";categorySectionField.style.display=categoryEditMode==="add"&&type==="expense"&&origin==="transaction"?"block":"none";categoryOwnerLabel.textContent=type==="income"?"ATTRIBUTION DU REVENU":"ATTRIBUTION DE LA DÉPENSE";
 if(id){const base=categoriesForType(type).find(x=>x.id===id);if(!base)return;const c=categoryView(base,type);categoryEditKind.textContent=c.name;categoryNameField.style.display=mode==="planned"?"block":"none";categoryNameInput.value=c.name;if(ownerEditable)setCategoryEditOwner(c.owner||"common");if(mode==="actual"){const m=metrics(),a=(type==="income"?m.incMap:m.expMap)[c.id]||0,isSaving=type==="expense"&&!!base.saving;categoryEditTitle.textContent=isSaving?"Modifier l’épargne":type==="income"?"Modifier le revenu réel":"Modifier le réel";categoryAmountLabel.textContent=isSaving?"MONTANT RÉEL ÉPARGNÉ":type==="income"?"MONTANT RÉEL REÇU":"MONTANT RÉEL DÉPENSÉ";categoryBudgetInput.value=Number(a).toFixed(2);saveCategoryEdit.textContent=isSaving?"Enregistrer l’épargne":"Enregistrer le réel";saveCategoryEdit.className=type==="income"||isSaving?"btn btn-income save":"btn btn-ghost save"}else{setCategoryPlanScope("forward");categoryEditTitle.textContent=base.saving?"Modifier l’épargne prévue":"Modifier le prévu";categoryAmountLabel.textContent=base.saving?"MONTANT D’ÉPARGNE PRÉVU":"MONTANT PRÉVU";categoryBudgetInput.value=Number(c.budget||0).toFixed(2);saveCategoryEdit.textContent="Enregistrer le prévu";saveCategoryEdit.className="btn btn-income save"}}
 else{setCategoryEditOwner("common");if(type==="expense")setCategoryEditSection(section||"Vie courante");categoryPlanScopeField.style.display="none";categoryEditTitle.textContent=type==="income"?"Créer un revenu":"Créer une dépense";categoryEditKind.textContent=origin==="transaction"?"Nouveau champ pour cette opération":section||"Catégorie";categoryNameField.style.display="block";categoryNameInput.value="";categoryAmountLabel.textContent="MONTANT PRÉVU";categoryBudgetInput.value="";saveCategoryEdit.textContent="Créer le champ";saveCategoryEdit.className="btn btn-income save"}
 categoryEditBackdrop.classList.add("open");categoryEditBackdrop.setAttribute("aria-hidden","false");setTimeout(()=>{(id?categoryBudgetInput:categoryNameInput).focus()},70);
}
function closeCategoryEditor(){categoryEditBackdrop.classList.remove("open");categoryEditBackdrop.setAttribute("aria-hidden","true")}
function setCategoryActual(id,amount,type="expense",label="Ajustement manuel",meta={}){
 const current=totalsByCategory(type)[id]||0,target=Math.max(0,Math.round((Number(amount)||0)*100)/100),delta=Math.round((target-current)*100)/100;if(Math.abs(delta)<.005)return false;const c=catById(id,type),owner=c?planForCategory(c,state.selectedMonth,type).owner:"common";state.transactions.push({id:uid(),type,category:id,owner,amount:delta,date:transactionDateForSelectedMonth(),seed:false,adjustment:true,adjustmentLabel:label,...meta});return true
}
function setSectionActual(type,section,mode){const cats=type==="income"?visibleIncomeCategories():section==="__savings__"?visibleSavingCategories():visibleExpenseCategories().filter(c=>c.section===section),action=mode==="fill"?"Remplissage automatique":"Remise à zéro",groupName=type==="income"?"Revenus":section==="__savings__"?"Épargne":section,groupId=`bulk-${uid()}`,bulkLabel=`${groupName} · ${mode==="fill"?"tout remplir":"tout vider"}`;cats.forEach(c=>setCategoryActual(c.id,mode==="fill"?c.budget:0,type,action,{bulkGroupId:groupId,bulkLabel}));saveState();render()}
categoryGrid.addEventListener("click",e=>{const bulk=e.target.closest("[data-bulk-action]");if(bulk){setSectionActual(bulk.dataset.categoryType||"expense",bulk.dataset.section||"",bulk.dataset.bulkAction);return}const actual=e.target.closest("[data-edit-actual]");if(actual){openCategoryEditor(actual.dataset.editActual,null,"actual",actual.dataset.categoryType||"expense");return}const planned=e.target.closest("[data-edit-planned]");if(planned){openCategoryEditor(planned.dataset.editPlanned,null,"planned",planned.dataset.categoryType||"expense");return}const del=e.target.closest("[data-delete-category]");if(del){openCategoryDelete(del.dataset.deleteCategory,del.dataset.categoryType||"expense");return}const add=e.target.closest("[data-add-category]");if(add){openCategoryEditor(null,add.dataset.addCategory,"planned",add.dataset.categoryType||"expense");return}const addSaving=e.target.closest("[data-add-saving]");if(addSaving)openModal("saving")});
function renameCategory(id,type,name){name=String(name||"").trim();if(!name)return;const map=type==="income"?(state.incomeCategoryNames=state.incomeCategoryNames||{}):(state.categoryNames=state.categoryNames||{});map[id]=name;const custom=type==="income"?state.customIncomeCategories:state.customExpenseCategories,found=custom.find(c=>c.id===id);if(found)found.name=name;const c=catById(id,type);if(c)c.name=name}
document.getElementById("closeCategoryEdit").addEventListener("click",closeCategoryEditor);categoryEditBackdrop.addEventListener("click",e=>{if(e.target===categoryEditBackdrop)closeCategoryEditor()});
saveCategoryEdit.addEventListener("click",()=>{const amount=Math.max(0,Math.round((Number(categoryBudgetInput.value)||0)*100)/100);let createdId=null;if(categoryEditMode==="planned"){const c=categoriesForType(categoryEditType).find(x=>x.id===categoryEditId);if(!c)return;const newName=categoryNameInput.value.trim();if(newName)renameCategory(c.id,categoryEditType,newName);setCategoryPlan(c.id,categoryEditType,amount,categoryEditOwner,categoryPlanScope)}else if(categoryEditMode==="actual"){const c=catById(categoryEditId,categoryEditType),label=c?.saving?"Ajustement épargne":"Ajustement manuel";setCategoryActual(categoryEditId,amount,categoryEditType,label)}else{const name=categoryNameInput.value.trim();if(!name)return categoryNameInput.focus();const createdFrom=monthKey(state.selectedMonth);if(categoryEditType==="income"){const c={id:`custom-income-${uid()}`,name,budget:amount,owner:categoryEditOwner,custom:true,createdFrom};createdId=c.id;INCOME_CATEGORIES.push(c);state.customIncomeCategories.push({...c});state.incomeBudgets[c.id]=amount;state.incomeCategoryOwners[c.id]=categoryEditOwner}else{const c={id:`custom-${uid()}`,name,budget:amount,section:categoryEditSection||"Vie courante",owner:categoryEditOwner,custom:true,createdFrom};createdId=c.id;EXPENSE_CATEGORIES.push(c);state.customExpenseCategories.push({...c});state.categoryBudgets[c.id]=amount;state.categoryOwners[c.id]=categoryEditOwner}}saveState();closeCategoryEditor();render();if(createdId&&categoryEditOrigin==="transaction")selectCreatedTransactionCategory(createdId)});

let categoryDeleteId=null,categoryDeleteType="expense";const categoryDeleteBackdrop=document.getElementById("categoryDeleteBackdrop"),categoryDeleteName=document.getElementById("categoryDeleteName"),categoryDeleteKind=document.getElementById("categoryDeleteKind");
function openCategoryDelete(id,type="expense"){const c=categoriesForType(type).find(x=>x.id===id);if(!c)return;categoryDeleteId=id;categoryDeleteType=type;categoryDeleteName.textContent=c.name;categoryDeleteKind.textContent=state.selectedMonth;categoryDeleteBackdrop.classList.add("open");categoryDeleteBackdrop.setAttribute("aria-hidden","false")}
function closeCategoryDelete(){categoryDeleteBackdrop.classList.remove("open");categoryDeleteBackdrop.setAttribute("aria-hidden","true");categoryDeleteId=null;categoryDeleteType="expense"}
function deleteCategoryForMonth(){if(!categoryDeleteId)return;const key=monthKey(state.selectedMonth),store=categoryDeleteType==="income"?(state.deletedIncomeCategoryMonths=state.deletedIncomeCategoryMonths||{}):(state.deletedCategoryMonths=state.deletedCategoryMonths||{});const list=new Set(store[key]||[]);list.add(categoryDeleteId);store[key]=[...list];saveState();closeCategoryDelete();render()}
function deleteCategoryForAllMonths(){if(!categoryDeleteId)return;const globalKey=categoryDeleteType==="income"?"deletedIncomeCategoriesGlobal":"deletedCategoriesGlobal",monthKeyName=categoryDeleteType==="income"?"deletedIncomeCategoryMonths":"deletedCategoryMonths";state[globalKey]=Array.isArray(state[globalKey])?state[globalKey]:[];if(!state[globalKey].includes(categoryDeleteId))state[globalKey].push(categoryDeleteId);Object.keys(state[monthKeyName]||{}).forEach(key=>{state[monthKeyName][key]=(state[monthKeyName][key]||[]).filter(id=>id!==categoryDeleteId);if(!state[monthKeyName][key].length)delete state[monthKeyName][key]});saveState();closeCategoryDelete();render()}
document.getElementById("closeCategoryDelete").addEventListener("click",closeCategoryDelete);document.getElementById("cancelCategoryDelete").addEventListener("click",closeCategoryDelete);document.getElementById("deleteCategoryMonth").addEventListener("click",deleteCategoryForMonth);document.getElementById("deleteCategoryAll").addEventListener("click",deleteCategoryForAllMonths);categoryDeleteBackdrop.addEventListener("click",e=>{if(e.target===categoryDeleteBackdrop)closeCategoryDelete()});
